### ISSUE TITLE
Get native un-tarring working on Linux and OSX and investigate native unzipping on Windows.

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#10]
http://superuser.com/questions/600943/unzip-file-from-source-to-destination-within-user-directory-across-multiple-vers?rq=1

**Comment by umlaeute** [comment]
btw, [in the code](/pure-data/deken/blob/ade982a/deken-plugin.tcl#L153) you mention:

> NOTE: in tcl 8.5 it should be possible to use the zlib interface to actually do the unzip

afaict, `zlib` is included since tcl-8.6 (at least my w32 install of tcl/tk8.5 doesn't have it)

**Comment by chr15m** [comment]
Yep, that's right.

Also see #9.

**Comment by umlaeute** [comment]
## search
searches for a given library, and returns all matches

arguments:
- search string (can be empty)

returned data:
- a set of
 - description of the package (file), so the user knows what they are to install
 - trust establishing description: so the user knows who provided that binary
 - how well does the given package match the host?
 - an ID, that can be passed to the `install` routine

the host sorts the returned values along the match axis (and probably along the date/version axis)

## install
installs a given library

arguments:
- ID (as returned by `search`)

returned data:
- success?
- installation progress
  + directly write into the deken-window? (requires to pass `$mytoplevel.results`)

**Comment by umlaeute** [comment]
note that this still doesn't have native unzipping on w32...
