### ISSUE TITLE
how to handle duplicates? 

### ISSUE THREAD

**Issue by PedroLopes** [pure-data/deken#100]
Dear pd-denken devs,

Thanks so much for this awesome tool. I'm having a blast with it, I think this will greatly contribute to pd as a whole. 

I was wondering about duplicates: 
If I already have a lib (e.g., one that comes with Pd) the deken will download it again:
- the new one will land at 
- the old one (bundled with Pd) lives at:
  The plugin does correctly identify that (which is awesome!) and reports:
  WARNING: duplicate 'jmmmp' library found!
  '/Users/pedro/Library/Pd/jmmmp' is active
  '/Applications/Pd-extended.app/Contents/Resources/extra/jmmmp' is duplicate

Note that it also activated the new one without prompting me (i think its fine, but will take some extra effort in case the user actually wanted the old one and not the new one, I'm assuming I would do >rm Users/pedro/Library/Pd/jmmmp and it will default back to the one on /extra)

I feel like the possible way to do this would be similar to what apt, easy_install, pip, etc do:
- alert user the lib/external  already installed, not install a new one
- if lib/external version number has been upgraded, propose a upgrade (i.e., replace with new).

How's this for a suggestion? Are version numbers possible in the current arch?

**Comment by umlaeute** [comment]
Deken *only* searches for libs and "installs" them in a place that pd searches for, nothing else.

It neither "activates" them (either the user or a patch does that[*]) nor warns about multiple installations (pd does that).


[*] there's a 3rd option: gui plugins will be automatically loaded by pd, so they are kind of "auto-activated"

**Comment by PedroLopes** [comment]
Thanks for your answer. 
Then should I guess PD is the one saying " '/Users/pedro/Library/Pd/jmmmp' is active ". 

Perhaps what happens when the same plugin is installed again via deken should be handled/discussed at Pd level?

**Comment by umlaeute** [comment]
yes, it's Pd that writes that "error" (somewhen in [helpbrowser.tcl](https://github.com/pure-data/pure-data/blob/master/tcl/helpbrowser.tcl#L234)).

i'm not sure what would be the correct resolution: Pd complains because it can access a single namespace (e.g. `jmmmp`) via multiple paths (e.g. `/Users/pedro/Library/Pd/` and `/Library/Pd`) and one is taking precedence over the other(s) - the "error" message is merely there to tell you which namespace is the "most" active one.

**Comment by umlaeute** [comment]
related issue: #149

**Comment by umlaeute** [comment]
given that the deken-plugin now "uninstalls" a library (well it deletes the relevant directory) before (re)installing it, i think this can be closed.

if you disagree, please speak up and provide ideas how to actually solve the issue.
i'll happily re-open the issue then (or you could just create a new one).
