### ISSUE TITLE
select python version (ubuntu) as deken complains about v2.7 (InsecurePlatformWarning)

### ISSUE THREAD

**Issue by electrickery** [pure-data/deken#104]
On (X)ubuntu version 14.04 LTS the default python is 2.7. This version is required for maintenance. Newer versions can be installed, but 2.7 needs to be the default version. Deken wants a newer version as it complains loudly during upload:

/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

Is it possible to start deken with a non-default python?

**Comment by umlaeute** [comment]
hmm, i'm using python2.7 on my Debian systems without problems.

    $ python2.7 --version
    Python 2.7.11
    $

you can also try installing most dependencies of `deken` via `apt` rather than locally via `pip`

**Comment by umlaeute** [comment]
also on my system, `deken` installed a local version of `python2.7` via `pip`:

    $ ~/.deken/virtualenv/bin/python2.7  --version
    Python 2.7.10
    $


ah, and according to [packages.debian.org](http://packages.ubuntu.com/search?keywords=python2.7&suite=trusty), *Ubuntu 14.04 LTS* ships with `python2.7_2.7.6-8ubuntu0.2`, which is definitely older.

**Comment by electrickery** [comment]
@umlaeute: I can install a newer version of python with apt, but that doesn't change the version in ~/.deken/virtualenv/bin/, which is Python 2.7.6. 
It surprises me that deken manages to install different python versions for different systems.

**Comment by chr15m** [comment]
@electrickery can you try the PR above and see if it fixes the issue for you? You may have to do a fresh install of deken.

**Comment by electrickery** [comment]
@hr15m: it doesn't seem to have much effect. This is what I did:
- cleanup of ~/.deken and ~/bin/deken
- getting bin delek again with curl and execute
- add the three lines to ~/.deken/requirements.txt
- execute 'deken upload <dekenPakage>'

Two types of error/warning messages, the first one once, the second one 15 times:
Uploading cyclone-0.2beta1(Windows-i386-32)(Sources)-externals.zip.sha256 to https://puredata.info/Members/fjkraan/software/cyclone-0.2beta1/
/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
...

**Comment by electrickery** [comment]
@chr15m: tried deken upgrade too, to see what would happen. It starts downloading stuff but also produce errors/warnings:
...
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found

...

You are using pip version 6.1.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

...
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/c
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/home/fjkraan/.deken/virtualenv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ybvixx/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DcX4mE-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/fjkraan/.deken/virtualenv/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-Ybvixx/cffi
Successfully upgraded.

**Comment by Ant1r** [comment]
I had to install first (with apt-get) `libffi-dev` and `python-dev`, before `deken upgrade` without error. Then `deken upload` perfectly !

**Comment by electrickery** [comment]
@Ant1r  Thank you! I also had to install libssl-dev (and maybe libssl1.0.0-dbg), but now the upgrades succeeds without errors. And the upload runs without insecurity messages. It is quite confusing that deken appears to have its own environment, but still depends on the generic one.
