### ISSUE TITLE
Allow the user to specify the path where they would like the upload to go.

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#11]
e.g. make the (default) destination `/downloads/${NAME}/${VERSION}/`

ideally the destination would be settable by the user.

**Comment by umlaeute** [comment]
i'm really speaking with my admin hat on: whenever the website migrates to a more up-to-date version of plone (or whatever), we (iem) intend to put priority on the downloads section (and less so on the Member's homes which has become a dumping place of sorts)

**Comment by chr15m** [comment]
Ok, will check this out, thanks @umlaeute IOhannes! Does every user have write access to those locations?

**Comment by umlaeute** [comment]
iirc, it's like this:
- every user can create a new project `/downloads/${NAME}/`
- only the owner of a given project can upload new versions to their project

pitfalls to be aware of:
- when automatically creating a new version folder `/downloads/${NAME}/releases/${VERSION}`, you need to provide some information (iirc, both the license and a short release summary are mandatory).

**Comment by chr15m** [comment]
Ok, cool. I'll have to investigate if and how that can be done via webdav as that is the mechanism I am currently using. Otherwise I'll have to look at mechanize or similar to perform the upload.

**Comment by chr15m** [comment]
Keep a command line option "--home" which allows the user to upload into their homedir on puredata.info instead.

**Comment by umlaeute** [comment]
urgh: a quick and dirty check to use `cadaver` to create *anything* in the `/downloads/` section, failed abysmally :-(

**Comment by umlaeute** [comment]
in any case, the upload target should be configurable (so people can choose to upload to `/Members/${UID}/software`, or wherever.

**Comment by chr15m** [comment]
I didn't have any success with uploading to other folders I created through the web interface but maybe you will fare better.

**Comment by umlaeute** [comment]
you didn't have success with your code or with mine?

because mine did fix that issue

though i just noticed that i have broken something else in my last commit c3dc2458.
with "something else" rendering the entire "upload" unusable.

i'll commit a fix in a second.
