### ISSUE TITLE
Ambiguous logging during signing

### ISSUE THREAD

**Issue by electrickery** [pure-data/deken#110]
While signing a package, deken first reports first that no signing will occur and then happily starts signing. There might be a context in which this makes sense, but from my standpoint it is confusing.
This happens during 'deken package' or 'deken upload' if no signing files are present.

Example:
in order to sign cyclone-vx.y-(Linux-amd64-64)-externals.tar.gz
Enter GPG passphrase: 
No valid GPG key found (continue without signing)
[GNUPG:] USERID_HINT 01234567890ABCDEF Fred Jan Kraan <fjkraan@xs4all.nl>
[GNUPG:] NEED_PASSPHRASE 01234567890ABCDEF 01234567890ABCDEF 1 0
[GNUPG:] GOOD_PASSPHRASE
[GNUPG:] BEGIN_SIGNING
[GNUPG:] SIG_CREATED D 1 2 00 ....

**Comment by umlaeute** [comment]
:+1:
