### ISSUE TITLE
should we make the 'version' mandatory?

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#111]
i think the default for all packages should be to have a `version` associated with them.

if the user tries to create a package without a version, the default should be to *fail* (and suggest to use a date-based version like `0.20151224`)

     $ deken package unversionedlib/
     No version for 'unversionedlib'.
     If 'unversionedlib' doesn't have a proper version number, 
         consider using a date-based fake version like '0.20151225'.
     $ echo $?
     1
     $

if the user desparately wants to have an unversioned package, they should be allowed to specify an empty version:

     $ deken package -v "" unversionedlib/
     $ echo $?
     0
     $

**Comment by umlaeute** [comment]
for what it is worth, so far we have a few unversioned libraries uploaded to puredata.info.
incidentally most of them are uploaded by @chr15m, and a few by @avilleret. maybe they could be fixed?

~~~
http://puredata.info/Members/avilleret/software/Cream(Linux-amd64-64)-externals.tar.gz
http://puredata.info/Members/avilleret/software/mediasettings/mediasettings(Linux-armv6-32)-externals.tar.gz
http://puredata.info/Members/chr15m/freeverb~(Darwin-i386-32)(Darwin-x86_64-32)-externals.zip
http://puredata.info/Members/chr15m/freeverb~(Linux-amd64-64)-externals.zip
http://puredata.info/Members/chr15m/freeverb~(Linux-armv6-32)-externals.zip
http://puredata.info/Members/chr15m/freeverb~(Windows-i386-32)-externals.zip
http://puredata.info/Members/chr15m/helloworld(Linux-amd64-64)-externals.zip
http://puredata.info/Members/chr15m/helloworld-osx(Darwin-i386-32)(Darwin-x86_64-32)-externals.zip
http://puredata.info/Members/chr15m/helloworld-rpi(Linux-armv6-32)-externals.zip
http://puredata.info/Members/chr15m/pdlua(Windows-i386-32)-externals.zip
http://puredata.info/Members/chr15m/plugin~(Windows-i386-32)-externals.zip
http://puredata.info/Members/chr15m/software/v0-0extended/blockhead/blockhead-externals.zip
~~~

**Comment by avilleret** [comment]
if renaming the files on puredata.info is enough, then it's done for me

**Comment by umlaeute** [comment]
yes that's great. thanks.
