### ISSUE TITLE
How to upload a library from windows?

### ISSUE THREAD

**Issue by jmmmp** [pure-data/deken#113]
How is it possible to upload a library from windows?

**Comment by umlaeute** [comment]
how is it not possible?
i guess you need to install python first.
once you have done that, `deken` should be able to bootstrap itself.
there's also ticket #15 about creating a native `deken.exe` or w32...

in the meantime it is probably simpler to either do it manually or just use a linux/osx machine (you can use `deken` with packages for other platforms)

the manual route:
- package: create a zip-file with the proper-name (see also #109)
- upload via the Plone-Software-Center
  - open your browser, go to https://puredata.info
  - log in
  - go to https://puredata.info/downloads
  - create a new project for your library (if you haven't done so)
  - create a new release for your library
  - upload the zip-file you just created

- alternatively upload to your home directory
  - open your browser, go to https://puredata.info
  - log in
  - go to your home-directory https://puredata.info/Members/...
  - create a new directory `software` via the *add new article* pulldown
  - within that folder, create a new directory for your library (e.g. `mylibrary`)
  - within *that* folder, create a new `File` and use it to upload the just created zip-file.

**Comment by jmmmp** [comment]
Great, the 2nd manual route worked very well (didn't try the other ones). I did get the errors below, but it doesn't bother me:

Unable to extract package automatically.
Please perform the following steps manually:
1. Unzip C:/Program Files (x86)/Common Files/Pd/jmmmp-v0.4.extended--externals.zip.
2. Copy the contents into C:/Program Files (x86)/Common Files/Pd.

**Comment by umlaeute** [comment]
I don't see an error.
can we close this issue?

**Comment by jmmmp** [comment]
From my side, yes. I didn't find any button here where I could do it.
