### ISSUE TITLE
Make ~/.deken workspace location configurable

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#12]
i just noticed that `deken` starts to download and build in `~/.deken/` (which i don't like due to hard disk size constraints).

is there a way to tell deken to use an alternative *workspace* (and place for the *virtualenv*, for that matter)?

**Comment by chr15m** [comment]
Not yet, but thanks for the feature request. Would it make sense to be able to set an environment variable like `DEKEN_HOME=/usr/local/deken`?

**Comment by umlaeute** [comment]
hmm, well yes.
but ideally it would be stored in some configuration file.

e.g.

    $ cat ~/.deken/config
    {
        "WORKSPACE_HOME":"/usr/local/deken/build",
        "VIRTUALENV_HOME":"/var/lib/virtualenv/deken"
    }
    $

**Comment by chr15m** [comment]
Ok, thanks.

**Comment by chr15m** [comment]
As a temporary measure you can symlink `~/.deken` to a folder on a different filesystem with more space.

**Comment by umlaeute** [comment]
additionally, deken should somehow use system installed things.
e.g. on Debian (#13) , the *default* should be to use the Pd-headers provided in `/usr/include/pd`, rather than downloading/building your own version (which should be possible, but *optional*).

**Comment by chr15m** [comment]
I am not sure if the Pd management and 'build' commands are that important to deken. I am wondering if we should remove that functionality and focus on just packaging + upload. What do you think?

**Comment by umlaeute** [comment]
:+1:

**Comment by umlaeute** [comment]
closing this, since
- [x] the symlink approach is reasonable enough to relocate the workspace
- [x] the `build` command is long gone
