### ISSUE TITLE
Add 'i686-32' as a valid platform for Windows/msys/minGW

### ISSUE THREAD

**Issue by electrickery** [pure-data/deken#125]
Currently the platform indicator for Windows packages is 'i386-32'. As the uname -m for both msys32/minGW and Cygwin report 'i686-32', it seems useful that the deken plug-in should accept this as a valid platform.

**Comment by umlaeute** [comment]
did you experience any actual problems?
because the deken-plugin should already handle `i686` as an *alias* for `i386`.

**Comment by umlaeute** [comment]
alsa, `deken` (the cmdline tool) does not use `uname` and will properly report `i386` anyhow.

but i guess your question is more targetted at using tools other than `deken` to get the arch-identifier (e.g. `Makefile.pdlibbuilder`)

**Comment by electrickery** [comment]
The issue is that even with the deken plugin version in 0.47.0, the Windows-i686-32 package in the list is grayed out. The Windows-i386-32 is properly in black. The i686-32 package is however downloadable. (See maxlib as example, used Windows 10 as OS).

De issue indeed appears with the usage of the experimental 'make deken' target of Makefile.pdlibbuilder which does use uname. For now it borrows the zip from CygWin, so it is not a convenient feature for Windows based building.
