### ISSUE TITLE
search apt for packages

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#13]
i would like to make `deken` available as an ordinary Debian package (for Debian and derivatives).

Since Debian already has a large number of Pd-externals available as debs, it would be great if we could find a way to integrate that into `deken` (with *that* i mean: *also* search for Debian-packages for the given library, and provide a way to install those)

**Comment by umlaeute** [comment]
https://bugs.debian.org/788075

**Comment by chr15m** [comment]
Wow, that would be cool. That type of integration would have to happen in the `deken-plugin.tcl` code - it could detect when the user is on a Debian derivative and then call `apt` or similar to perform the install.

**Comment by umlaeute** [comment]
since the Debian-part is of little use for w32/osx/... people, i wonder whether the proper way would be to have a hook that would allow for additional backends, without cluttering the core code too much...

**Comment by chr15m** [comment]
Ah, good idea. Because the plugin would be bundled via Debian anyway it would be possible to also bundle the special Debian-deken backend without making it onerous for the user.

**Comment by umlaeute** [comment]
note to myself: the virtualenv should be kept minimal, e.g. dependencies need to be pulled in via apt (global) rather than pip (local).

**Comment by chr15m** [comment]
Isn't this task supposed to be about packaging deken for Debian?

**Comment by chr15m** [comment]
Oh wait, no.
