### ISSUE TITLE
Text color same as background

### ISSUE THREAD

**Issue by acook** [pure-data/deken#130]
The background color I have is black, but the text is also black so I'm not able to see anything until I hover over items. Do I need to modify the TCL to specify the text color?

**Comment by umlaeute** [comment]
i assume that this problem is only about the `deken` dialog, correct?
which version of Pd are you using? which version of deken?

do you have any special GUI plugins loaded?

**Comment by acook** [comment]
Fresh install of Pd 0.46-7, and it's the version of Deken from github master as of the 21st, which is labeled 0.2.

**Comment by umlaeute** [comment]
please post a screenshot
(and detailed info about your window-manager,...)

**Comment by acook** [comment]
This is on OS X 10.11.4. 

Below I've hit the "show all" button and the screen is black, but when I hover over an item the invisible text turns to webbrowser-link-blue.

![may-28-2016 13-43-35-clip](https://cloud.githubusercontent.com/assets/71984/15629274/72e0d716-24da-11e6-81c4-88ddac6e4d67.gif)

**Comment by umlaeute** [comment]
thanks for the screenshot.

so it is you yourself who changed the (Desktop?) theme to make the background color black (should have mentioned that first).
i guess that this only affects the `results` display (once you click on a result, the download "progress" should be "normal" (aka visible).

can you confirm that removing the `-foreground black` in [deken-plugin.tcl:246](https://github.com/pure-data/deken/blob/master/deken-plugin.tcl#L246) fixes the issue?

**Comment by acook** [comment]
OSX does not allow you much leeway in customization options, there's no themes or anything, no way to change the window background colors globally that I'm aware of (and if there is I haven't done it) and they are by default white. You can see the resize handle in the lower right is still white because of OSX's window decoration. (My editor there is Vim and it has its own configuration file and theme engine.)

I'm not even sure why Pd has an inverted color scheme, but all the other windows seem to work just fine with it. Removing that line does make the text visible again. It doesn't seem to have any trouble returning to the grey-white foreground color after being hovered over either.

<img width="673" alt="screen shot 2016-05-30 at 15 06 15" src="https://cloud.githubusercontent.com/assets/71984/15657628/2b580c9e-2678-11e6-8175-a6e9dcc5db33.png">

It looks like I captured a minor redraw issue in my above screenshot, where the status bar text overlays the "Install" button text, but that's something different.

**Comment by umlaeute** [comment]
i still wonder how you managed to make the background *black*.
This is *not* something that Pd does by itself nor can it give you the power to do so.

so you must have done something else to trigger that problem.

**Comment by acook** [comment]
I figured it out, I share configuration files across multiple systems and there's a `.Xdefaults` file in my home directory which Pd is picking up which sets the default foreground and background colors to grey/black.

**Comment by osirisgothra** [comment]
Its good to note that some distros will set an .Xdefaults which then gets picked up, I have a rather older version that did this, which used a dark theme by default, so it set .Xdefaults this way. It was actually this thread here that allowed me to pinpoint it.
