### ISSUE TITLE
Problem installing and using deken on Linux

### ISSUE THREAD

**Issue by electrickery** [pure-data/deken#137]
Due to a fresh install of Xubuntu 16.04-64 bit, I had to install the deken tool again. Here I ran into some problems:
- it complains about a missing module datetime
- default there is no pip, had to install this; "sudo apt install python-pip"
- ran deken upgrade (to make sure everything is working and up to date). This finally complained about not importing datetime before declaring the upgrade a success.
- attempted an upload, which complaines again about datetime
- attempted to "pip install datetime" which failed.

Some logs below.

Fred Jan

fjkraan@var64:~$ bin/deken
Traceback (most recent call last):
  File "/home/fjkraan/.deken/virtualenv/bin/hy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
ImportError: No module named datetime
fjkraan@var64:~$

install python-pip

deken upgrade

...
Traceback (most recent call last):
  File "/home/fjkraan/.deken/virtualenv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 22, in <module>
    from pip._vendor import pkg_resources
  File "/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 92, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.pkg_resources'
Successfully upgraded.

deken upload ....

Traceback (most recent call last):
  File "/home/fjkraan/.deken/virtualenv/bin/hy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/fjkraan/.deken/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
ImportError: No module named datetime

pip install datatime
Collecting datatime
  Could not find a version that satisfies the requirement datatime (from versions: )
No matching distribution found for datatime
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by electrickery** [comment]
Solved the issues above with the stackoverflow fix of recreating the virtualenv (had it copied over from the old xubuntu 14.04. Now the deken install ends with some compilation errors.

Deken upload works now as it should, so my problem is solved, but maybe there is still an issue for compilation.

(http://stackoverflow.com/questions/26031160/importerror-no-module-named-datetime)

    ...
    creating build/temp.linux-x86_64-2.7/c
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
    Command "/home/fjkraan/.deken/virtualenv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ExTYWX/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ljX6Sh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/fjkraan/.deken/virtualenv/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-ExTYWX/cffi
usage: deken [-h] [--version] {package,upload,upgrade} ...
deken: error: too few arguments

**Comment by umlaeute** [comment]
`apt-get install deken`

(though on xenial this gives you an outdated version)
