### ISSUE TITLE
Feature proposal plugin: add option to launch info page at puredata.info

### ISSUE THREAD

**Issue by electrickery** [pure-data/deken#138]
It would be nice as the user could obtain some more information before downloading an object package. It would mean the current click-and-download would be replaced by a click-to-select and buttons to initiate an action. 'Download' would start the download and 'More Info' would start the system default browser with the url of a fixed page in the directory of the selected package. 
The package uploader should provide this page with the additional data. "index.html" could be a sane name. The behaviour in case the page is not present is TBD.

![libobj_dl_mi_cropped](https://cloud.githubusercontent.com/assets/359491/20036597/64c837f8-a40c-11e6-989c-2d878c83a283.png)

**Comment by umlaeute** [comment]
nice idea.

however, the <kbd>Download</kbd>/<kbd>More info</kbd> buttons should be visually distinct from the <kbd>Search</kbd> - e.g. in an other section of the window.


![deken_download info](https://cloud.githubusercontent.com/assets/214034/20050730/38f7852e-a4cb-11e6-947d-275a180ffe1b.png)

**Comment by electrickery** [comment]
On 07-11-16 09:20, umläute wrote:
> nice idea.
>
> however, the Download/More info buttons should be visually distinct from
> the Search - e.g. in an other section of the window.

Yes, the mockup is very ugly. I'll think maybe a left-click pop-up menu 
would be less invasive and has more room for expansion:

+--------------+
| List objects |  (loads package-version-objects.txt into browser)
| More info    |  (loads info page into browser)
| Install      |  (does the same as right click)
+--------------+

So I'll try to get this working first.

**Comment by electrickery** [comment]
It is not production ready, but almost demo ready, handy for next week. The only modification server side is making mime-type of text files agreable for a browser. Now it wants to download the file or open another application. 

![popupmenu](https://cloud.githubusercontent.com/assets/359491/20189902/6a69bc9c-a77f-11e6-82bf-af92263a2947.png)

The http://puredata.info/Members/fjkraan/software/tof/0.2.1 directory has the complete set of (demo) files.

[pd_deken.tcl.gz](https://github.com/pure-data/deken/files/584002/pd_deken.tcl.gz)

The 'current last' issue is that I can't destroy the popup menu, or find a way to reuse it. So it complains directly after clicking the menu and when you want to use it again (next Right-click).

**Comment by electrickery** [comment]
@umlaeute: only now I properly register the icon/buttons in your image. Having them added at show_result time probably solves the create/distroy issue at Right-click time.

**Comment by electrickery** [comment]
The popupMenu version is now working, at least for demo purposes. I could try to push it in a separate branch. 
Didn't pursue the buttons version yet, as I haven't found a mechanism to add buttons to a text-widget.

**Comment by electrickery** [comment]
This is the version as demoed at PdCon16. A final version would require better structure and a better landing page name for the "More Info" option, now called "moreInfo". puredata.info is a wiki, so index.html is not an automatic default.
/home/fjkraan/oldHome/PureData/deken-plugin.tar.gz

**Comment by umlaeute** [comment]
would you mind doing a pull-request? (prefix it with `[WIP]` if you are not sure about merging it right now).

**Comment by electrickery** [comment]
On 27-11-16 21:12, umläute wrote:
> would you mind doing a pull-request? (prefix it with |[WIP]| if you are
> not sure about merging it right now).

That would mean an actual fork instead of a private git clone as it is 
now. But if you think the current approach is heading in the right 
direction, I will try to create something pull and merge worthy.

In the meanwhile, we could find a better name for the landing page.

Greetings,

Fred Jan

**Comment by umlaeute** [comment]
mention #139

**Comment by umlaeute** [comment]
how about just opening the folder (on the webserver) that contains the deken-package.
e.g. for 

- http://puredata.info/Members/fjkraan/software/tof/0.2.1/tof-v0.2.1-(Darwin-ppc-32)(Darwin-i386-32)(Darwin-amd64-32)(Sources)-externals.tgz

the page that would open is http://puredata.info/Members/fjkraan/software/tof/0.2.1/

(as would be for all other packages in this directory).

You can either manually create an `index.html` page in this directory (via the webinterface), which will then be shown instead of the folder listing.
Or just create any other `page` and move it to the top of the folder listing, so people see it immediately when they access the directory).

The good thing about this is, that the folder is guaranteed to exist, so you won't get a 404 (or require the plugin to check beforehand).
(btw, this might already be what you are doing; i haven't really checked for some time)
