### ISSUE TITLE
Try to run GnuPG to generate a .sig file signing the package with the user's default key (if configured).

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#14]
https://pypi.python.org/pypi/gnupg

Allow user to specify an alternate key to sign with in the config.

**Comment by umlaeute** [comment]
cool.

however, related to @electrickery's comment in #9, i was wondering why this does not use the `default-key` as configured in my `~/gnupg/gpg.conf` file, but just the first available one (in my case an old expired key, that i keep around to be able to decode)

**Comment by umlaeute** [comment]
fixed the `default-key` issue in [95f0b242698]
