### ISSUE TITLE
feature request: remember last path between restarts

### ISSUE THREAD

**Issue by porres** [pure-data/deken#140]
I hope that deken remembers last path I chose to install the libraries

cause I usually like to install it in a different place - inside the Pd app, where it is only valid for that pd app, and not to extended, for instance, which I also use...

seems like a change that won't affect the user experience very much, and it'd be really useful for people like me

thanks

**Comment by umlaeute** [comment]
This depends builds on a rewritten gui-preference system for Pd, for which i'm currently preparing a PR.

**Comment by umlaeute** [comment]
the Pd-feature required can be found in pure-data/puredata#48
