### ISSUE TITLE
getting rid of internal config-storage

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#141]
is anybody using the configuration file for the `deken-plugin`?

it seems that nobody knows of its existence: even I (being the author) completely forgot about it, else i wouldn't have written e.g. c728107c.

instead i would rather replace that with a central GUI-storage mechanism from Pd (which is currently implemented suboptimally, but this could be fixed). 

this directly relates to #131 

it also somehow relates to #140 (as the current implementation is read-only)

**Comment by umlaeute** [comment]
just pinging @chr15m  and @danomatika for their input (rather than assigning this to them)

**Comment by danomatika** [comment]
Where is the info being stored currently? In Pd, then fed into the plugin when it's started?

Also, I've thought about merging the various preferences panes into some sort of tabbed panel ala Jonathan Wilke's work with tsk::Notebook. Adding an "Externals" section to config deke there might make sense.

**Comment by chr15m** [comment]
@umlaeute I am not using that config file for anything. You suggestion sounds good to me. :+1:

**Comment by umlaeute** [comment]
@danomatika currently the deken-plugin actively looks for a `deken-plugin.conf` in various search paths (including the ones from Pd).
there are two issues with the current approach:
- it's read-only
- it just imports *anything* declared in the config-file into the `::deken` namespace (which could potentially be a problem)
