### ISSUE TITLE
optionally open up README after successfull installation.

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#142]
oftentimes users are a bit lost after they downloaded a package via deken.
E.g. *zexy*-users are used to a Pd-extended style multi-binary library, but thye *might* get a multi-object single-file `zexy.dll` which doesn't work "as expected".

A README might help

**Comment by umlaeute** [comment]
I'm currently thinking of using special filenames (to give specific information for to deken-users; these could refer to more generic instructions if needed)

- `README.deken.pd`
- `README.deken.txt`
- `README.deken.html`

The entire package would be searched for these files, and if there are any, the user should be asked whether they want to open the README. (The decision could be remembered.)

**Comment by chr15m** [comment]
This solution sounds good to me. :+1:

**Comment by danomatika** [comment]
Is this something we can do now for the Pd 0.48.0 release? It would really help in stopping all the "I installed Gem via Deken but it doesn't work!!!??!" emails...

**Comment by umlaeute** [comment]
implementation has not started yet.
