### ISSUE TITLE
Re-installing does not fully replace previous installation

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#146]
Files from a previous package download remain in the folder when the those files are not part of the current download. The content of the resulting external folder is not identical with content of the most recent downloaded package. 

I believe the resulting folder should contain only files from the most recent download.

Maybe Deken should wipe the old directory before extracting the new archive over it.

**Comment by umlaeute** [comment]
the problem is, that deken doesn't know which directories are created.
it just blindly extracts the archive.
