### ISSUE TITLE
Finish the Windows build

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#15]

**Comment by umlaeute** [comment]
i always wondered what this ticket was about.

should it be closed?

**Comment by chr15m** [comment]
Probably. If somebody is requires deken to run on the Windows platform hopefully we'll get some pull-requests for that.

**Comment by chr15m** [comment]
What the ticket was about was getting a native executable built using e.g. py2exe I think. If somebody has e.g. cygwin hopefully it should work there.

**Comment by umlaeute** [comment]
implemented in ceffdf4db56073d9ba31c71c492e58be0b558e9d...bbf61ed4247c77d6828d6459c2e4bae27394290c using [PyInstaller](http://www.pyinstaller.org/).

we can easily generate a self-contained `deken.exe`!
