### ISSUE TITLE
deken.hy broken on Debian/buster

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#150]
`deken.hy` seems to be completely broken.

e.g. it uses `try`/`catch` rather than `try`/`except`, leading to errors like:

~~~
   (catch [e ImportError] (import [configparser [SafeConfigParser]])))
   ^----------------------------------------------------------------^
HyTypeError: Unknown expression in `try'
~~~

once i replaced all `catch` with `except` I now get:
~~~
    (let [[system-name (platform.system)]]
    ^-------------------------------------
      (cond
  ---------
        [(in system-name ["Linux" "FreeBSD"]) (os.path.expandvars (os.path.join "$HOME" "pd-externals"))]
  -------------------------------------------------------------------------------------------------------
        [(= system-name "Darwin") (os.path.expandvars (os.path.join "$HOME" "Library" "Pd"))]
  -------------------------------------------------------------------------------------------
        [(= system-name "Windows") (os.path.expandvars (os.path.join "%AppData%" "Pd"))])))
  ---------------------------------------------------------------------------------------^
HyTypeError: `setv' needs an even number of arguments
~~~

**Comment by umlaeute** [comment]
it seems that the `catch` keyword has been removed with `hy-0.12` (Debian/buster has `0.12.1-2`)

**Comment by chr15m** [comment]
@umlaeute yes 0.12 breaks a bunch of compatibility, and the next release will break even more. I think it's best to run inside a virtualenv with hy pinned to the correct version. This is what the `deken` bash script does when it bootstraps the script.

**Comment by umlaeute** [comment]
i think it is best to keep the code compatible to *all* (even future) hy versions.
afaics, bringing the code up to hy-0.12, will still keep it working on hy-0.11. i expect the same for hy-0.13.

in any case: true, this requires maintainance.
but i think that depening on some outdated runtime (say, *Win95*) is not an option.
(and any unmaintained code is dead anyhow, and should probably not be advertised)

**Comment by chr15m** [comment]
This is awesome, thanks @umlaeute!
