### ISSUE TITLE
empty search redundancy

### ISSUE THREAD

**Issue by porres** [pure-data/deken#154]
Howdy, deken says: "To get a list of all available externals, try an empty search" - but this seems obvious with the "show all" button, when the search field is empty - meaning that maybe it is not needed at all

**Comment by umlaeute** [comment]
so what is your suggestion? which problem would it fix?

Also deken keeps saying  "To get a list of all available externals, try an empty search" even if the user started to type something into the search-bar (which changes the button to <kbd>Search</kbd>, until they delete all text).
So I think this might help the inexperienced users to get back to "search all", while it doesn't add any  cognitive load for those who already know.

**Comment by porres** [comment]
> So I think this might help the inexperienced users to get back to "search all", while it doesn't add any cognitive load for those who already know.

I see, closing it
