### ISSUE TITLE
Can we use flavio's external-detection script somehow to suggest packages to search for?

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#16]
http://puredata.info/Members/federico/misc/pd-deps/at_download/file

Also Joe's idea of being able to right-click on dotted boxes to initiate a search.

**Comment by umlaeute** [comment]
i'm afraid that the right-click on dotted boxes requires substantial changes to Pd-core (just telling)

**Comment by chr15m** [comment]
Ok, that's good to know. I guess that feature will not be implemented soon.

**Comment by umlaeute** [comment]
btw, the script in the above URL simply outputs all non-vanilla objects.
there's no heuristic telling where these objects came from.

also the vanilla-objects are defined via an in-script list.

i do think that this could be done better (but would probably require an external)

**Comment by danomatika** [comment]
I think this is a "nice to have" right now but not a requirement.

**Comment by chr15m** [comment]
For sure it's low priority. I wish there was some way of indicating task priority in Github. For me the top priorities are #14 getting GPG signing of packages working (I am working on that now) and #9 - using tar.gz instead of zip on OSX and Linux. After we have the basics solid I'd like to get a bunch of packages uploaded and encourage Pd users to test the system.

**Comment by danomatika** [comment]
Use Github Labels. There are some default ones, but I created a High Priority label and applied it to those issues.

**Comment by danomatika** [comment]
You can also create a beta Milestone and add all the issues that need to be closed to it to track progress.

**Comment by umlaeute** [comment]
i think this has been obsoleted: we can now search for *objects* (at least if the uploader provided an objects-list)

there's also https://github.com/pure-data/pure-data/pull/1547 to ease the search for missing objects.
