### ISSUE TITLE
Zero results

### ISSUE THREAD

**Issue by mxa** [pure-data/deken#164]
I currently experience a Deken completely disfunctional. When entering a search term, the results stay empty.
![screenshot from 2017-09-06 15-25-09](https://user-images.githubusercontent.com/1220707/30503551-f2728982-9a6a-11e7-8a74-b3ff1257e019.png)

When starting up I see three lines in the console related to deken loading:

```
deken-plugin.tcl (Pd externals search) in /home/max/pd-externals loaded.
'deken-plugin.tcl' already loaded, ignoring: '/usr/lib/pd/extra/deken-plugin/deken-plugin.tcl'
'deken-plugin.tcl' already loaded, ignoring: '/home/max/pd-externals/deken-plugin.tcl' 
```

**Comment by umlaeute** [comment]
what's the output at the Pd-console (with verbosity **ALL**) and on the terminal?

you should have a line like the following, near the top of the Pd-console (right after all automatically loaded externals appeared; but before any automatically loaded gui-plugins)
> Loading plugin: /usr/lib/puredata/tcl/pd_deken.tcl

what's the version of the deken-plugin found in /home/max/pd-externals ?
(very old versions of deken might unconditionally override the built-in version)
most probably you ought to remove that leftover version.

**Comment by mxa** [comment]
Right! Switched to debug level 4 (all) and saw the deken plugin loading and then again loading from /home/max/pd-externals.
After deleting this later version I get a functional Deken plugin again.
Thank you.

**Comment by mxa** [comment]
It still loads another one

```
deken-plugin.tcl (Pd externals search) in /usr/lib/pd/extra/deken-plugin loaded.
Platform detected: Linux-x86_64-64bit
```
I probably should delete this one too, but then I loose Deken in older versions of Pd..

**Comment by umlaeute** [comment]
they should be reported, like.
~~~
Loading plugin: /usr/lib/puredata/tcl/pd_deken.tcl
[deken] Platform detected: Linux-x86_64-64bit
...
Loading plugin: /usr/lib/pd/extra/deken-plugin/deken-plugin.tcl
[deken]: installed version [0.2.3] > 0.2.1...skipping!
~~~

to manually check, look for the [versioncheck line](https://github.com/pure-data/deken/blob/d9f5cfb5b820a90238eceecc8cbb31c6f7d30235/deken-plugin.tcl#L62)
