### ISSUE TITLE
UnicodeDecodeError when uploading package from Travis

### ISSUE THREAD

**Issue by avilleret** [pure-data/deken#166]
this is related to https://github.com/pure-data/deken/issues/71
but since it was closed 2 years ago, I open a new one.

The configuration is quite different because I'm trying to upload package from Travis build.
So it runs on Ubuntu 14.04 and Python 2.7.

Deken installs fine but when uploading I got : 

```
Packaging ossia-v0.0-test1-(Linux-amd64-64)-externals.tar.gz
Attempting to GPG sign 'ossia-v0.0-test1-(Linux-amd64-64)-externals.tar.gz'
Traceback (most recent call last):
  File "/home/travis/.deken/virtualenv/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/home/travis/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/travis/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/home/travis/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/home/travis/.deken/virtualenv/local/lib/python2.7/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/home/travis/.deken/deken.hy", line 794, in <module>
    
  File "/home/travis/.deken/deken.hy", line 534, in main
    (if command (command arguments) (.print_help arg-parser)))
  File "/home/travis/.deken/deken.hy", line 493, in _hy_anon_fn_54
    (x args.source))
  File "/home/travis/.deken/deken.hy", line 484, in _hy_anon_fn_53
    (name args.source)))
  File "/home/travis/.deken/deken.hy", line 416, in archive_extra
    (gpg-sign-file zipfile)
  File "/home/travis/.deken/deken.hy", line 309, in gpg_sign_file
    (do-gpg-sign-file filename signfile)))))
  File "/home/travis/.deken/deken.hy", line 533, in do_gpg_sign_file
    (setv command (.get commands (keyword arguments.command)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 76-77: ordinal not in range(128)
```

And Deken is up-to-date, a fresh install is made on each build.
Do you have any hints ?

Thanks a lot

**Comment by umlaeute** [comment]
i don't really have an idea (and I'm aware that you are currently not using `deken` to upload)

however:
- does this happen in the package or in the upload stage? when running `deken upload some/path/` deken will automatically run the `package` stage first; it might help to run `package` first and then run `upload` in a secondary step (either by passing the generated zip file, or the directory again; the former should be slightly faster, but for assessing the bug it shouldn't really matter)
- i've recently pushed a few fixes to the `deken` cmdline tool; none of them have been related to Unicode, but you might be lucky and not see the problem any more nevertheless

**Comment by avilleret** [comment]
as mentioned, Deken install its dependencies without problem
the error occurs in the upload step when Deken tries to sign the package.
iirc I get rid of this error by not installing GPG key.
Without a valid GPG key Deken didn't try to sign the package and upload it as is, I guess.

I'll try to trig another build that uses Deken to see if recent upgrade have fix this issue.

**Comment by umlaeute** [comment]
does this problem persist with `deken-0.3`?

afaict, the problem is really in Python2's broken unicode support when it comes to redirecting output (and Travis-CI obviously redirects the output to some pipe, so it can display it on the webpage).

https://stackoverflow.com/q/4545661/1169096

workarounds:
- use Python3 (if the `python` binary really is Python2, you should be able to use something like the following (you probably should ditch `~/.deken` first)

~~~
PYTHON_BIN=python3 deken install
~~~

- make sure that your GPG-key doesn't contain any non-ascii characters
- just ignore the error :-)

**Comment by umlaeute** [comment]
hy3 is (slowly) fading out Python2 support.
the default deken installer now uses Python3, so i think the problem is "fixed".
