### ISSUE TITLE
proxy (Firewall) seems not to work

### ISSUE THREAD

**Issue by kezb765** [pure-data/deken#167]
I tried deken on a maschine (Windows 7 / pd 0.48.0) where the Internet is reached via proxy. Deken did not succeed so I think there might be an issue with using the proxy? I didn't find any option to set the proxy address so I think there is no such function. Am I right? Should this be a new feature?

**Comment by umlaeute** [comment]
`deken` doesn't do anything about proxying.

i'm not sure whether it should.

**Comment by umlaeute** [comment]
and you might also try setting up a system-wide proxy, e.g. as described [here](https://bytealmanac.wordpress.com/2012/04/12/set-system-wide-proxy-httpsocks-on-windows-7/) (note that I haven't tested at all what bytealmanac suggests, and I don't know whether it might work or not; but please try it out and report back if that solves your problem)
