### ISSUE TITLE
how to specify which python to use for deken command line tool ?

### ISSUE THREAD

**Issue by avilleret** [pure-data/deken#168]
in my environment, deken installation fails with : 

```
Collecting cryptography>=0.7 (from pyOpenSSL==0.15.1->-r /home/travis/.deken/requirements.txt (line 9))
  Downloading cryptography-2.1.1.tar.gz (441kB)
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'
```

So I'm trying to figure out how to use python3 instead of python2.7 to run deken.
According to https://github.com/pure-data/deken/issues/119 is should run fine with both (though it doesn't but it might be due to a third party update ?) but how to choose ?

The full install log is here : https://gist.github.com/avilleret/ad662667ff28a8b0fab28ec8b2fbb290 (truncated from a Travis build log)

Thanks for any hint.

Antoine

**Comment by umlaeute** [comment]
currently you cannot.

#119 only refers to the `deken.hy` file being Py3 compatible.
(this is currently (only?) useful if you don't use the built-in install/upgrade routines, but e.g. those provided by the `deken` Debian package)

**Comment by avilleret** [comment]
I was asking because `cryptographic` module complains about Python < 3.
but the issue seems to be elsewhere.

**Comment by umlaeute** [comment]
sure.

i'm not saying that we shouldn't add a way to select a different python interpreter; currently there is none.
