### ISSUE TITLE
travis-ci: command line tool installer is broken

### ISSUE THREAD

**Issue by avilleret** [pure-data/deken#169]
some error occurs since 2 weeks like the one describe here : 
https://gist.github.com/avilleret/ad662667ff28a8b0fab28ec8b2fbb290
see #168 

also after deleting my `~/.deken` folder and `~/bin/deken` I'm not able anymore to install command line tool, while it used to work.

Here is my output  :
https://gist.github.com/avilleret/36259a37961a46307f16f34e377b12ab

I tried to disable cryptographic depensencies in requierements.txt with no luck.
Any hint to get it work again ?

Thanks

**Comment by umlaeute** [comment]
this seems to be a problem with the version of `setuptools` (e.g. as installed on Travis-CI), not necessarily a bug in `deken`.

**Comment by umlaeute** [comment]
on second thought, this seems to be really only a problem with the `cryptography` module.

how did you try to disable it? why were you out of luck?

**Comment by avilleret** [comment]
I was referring to some test I made on my laptop.
Updating setuptools helps a little bit but was not enough.

I remove the `cryptography` dependency by removing some module in requieremnts.txt (see https://github.com/avilleret/deken/blob/master/developer/requirements.txt)
But as you guess it also remove other needed dependencies and this is where I have no luck.

Finally I end up by using `curl` to upload hand made packages directly.

**Comment by umlaeute** [comment]
i think this has been fixed with 4e7657f81c31d8d72e54af2e5e18efd89d514aa5.
