### ISSUE TITLE
Deken failing to work in PD Vanilla (plus issues with installing libs manually)

### ISSUE THREAD

**Issue by benithebread** [pure-data/deken#173]
Hi there,

I freshly installed PD Vanilla 0.48.0. When trying to use the search function of PD (Help.../find externals), it returns this error message:

wrong # args: should be "::deken::status msg"
wrong # args: should be "::deken::status msg"
    while executing
"::deken::status "
    (command bound to event)

I tried to fix it by implementing deken manually (https://github.com/pure-data/deken). After I did so, the error-message does not occur, but no matter what I am searching for, I don't get any results.
I tried to implement some libraries completely manually, but again: It works neither in the app specific folder, nor in the global nor the user specific folders. After adding the needed flags, i receive that the concerned library could not be loaded...

I tried Pd-extended, it worked fine so far, but people told me, PD Vanilla is suppose to have a better performance, that's why I would like to change the system.

I am running PD on a MacbookPro 2017 on Mac OS Sierra (10.12.6)

**Comment by umlaeute** [comment]
please open multiple tickets if you have multiple issues.
also please post the full (deken-related) output when starting Pd and you raise the log-level to "all" (aka: 4).

**Comment by benithebread** [comment]
The error message is not postet in the pd-window, it's an extra window that appears.
I changed the log-level to 4 and here I send you all that is happening the PD-window:

------------------ done with main ----------------------
Connection from 'pd' to 'pd-gui' on 127.0.0.1:49668
Loading plugin: /Applications/Pd-0.47-0.app/Contents/Resources/Scripts/pd_deken.tcl
::tk::mac::OpenApplication  ++++++++++++
The Pd window filtered 4 lines
The Pd window filtered 5 lines

okay, no prob about the new ticket, sry for inconvenience. thx for help


<img width="1440" alt="bildschirmfoto 2017-12-19 um 12 28 57" src="https://user-images.githubusercontent.com/23319657/34155077-43a4d002-e4b8-11e7-8179-f81914ccfb59.png">
<img width="1440" alt="bildschirmfoto 2017-12-19 um 12 29 05" src="https://user-images.githubusercontent.com/23319657/34155080-44b4ce34-e4b8-11e7-8ef2-354fbea9809f.png">

**Comment by benithebread** [comment]
btw: this is when not implementing the deken-code from github manually

**Comment by umlaeute** [comment]
i would go with Pd-0.48-0 (rather than Pd-0.47-0)

**Comment by benithebread** [comment]
thank you,

I did before using Pd-0.47-0, same problem, actually I thought maybe an older build could fix it.

I remember that when I installed pd-extended (0.48.0), I had to install xcode and some other packages, could it be, that this is why the newer version is not working anymore?

**Comment by umlaeute** [comment]
- there is no pd-extended 0.48.0
- i'm pretty sure that Pd-0.47-0 and Pd-0.48-0 do not have the same problems, as the deken code has been revamped between the two.
- fwiw, there's even Pd-0.47-1 which is the first *bugfix* release of Pd-0.47

anyhow, afaict the issue has been fixed and you can use either the built-in deken or a manually installed one (the real problem was that the deken-server had problems).

before i forgot: if you want to help *implementing* deken, PRs are always welcome :-)
