### ISSUE TITLE
Stop deken from filtering out architecture-independent packages with no (arch) strings

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#18]
for platform-independent packages (abstraction libraries, gui plugins), `deken package` leaves out the architecture field, e.g.

~~~~
$ deken package list-abs
Deken 0.1
Packaging into list-abs-externals.zip
~~~~

Unfortunately the `deken-plugin.tcl` ignores these files, which makes it impossible to distribute architecture-independent libraries (and no, i don't think that `list-abs-(Linux-x86_64-64)(Linux-i386-32)(Darwin-i386-32)(Darwin-x86_64-32)(Windows-i386-32)(Windows-amd64-64)-externals.zip` is the way to go :-))

note: i did my tests with a dummy-library not containing dashes; no idea whether a name like `list-abs` imposes any problems.

**Comment by chr15m** [comment]
Good idea. Will fix.

**Comment by chr15m** [comment]
To your last point - the plone search forces hyphen-separated words to be considered separately. I don't think It'll match on "list-abs" so there should probably be a warning if the external has a name with a hyphen to change it to an underscore.

**Comment by danomatika** [comment]
I think it's too late for "list-abs" ... that would probably break a lot of patches which use import & declare.

**Comment by umlaeute** [comment]
@danomatika  :+1: 

i think one core feature of deken must be, that it doesn't require *any* changes on the externals-side: no renaming, no changes to the build-systems, no nothing.

**Comment by umlaeute** [comment]
actually i think that we shouldn't use the built-in plone search at all, as it has too many restrictions:
- it only returns the first *15* (or so) results
- it does not allow to search for path-elements, only for the title (and description) (the current search only works because the uploaded zip-files have no "visible" name (as opposed to the so called "short name", which is part of the URI) set, and thus use the filename as title. but plone allows to provide an arbitrary title to differentiate between human-readable (and human-exposed) and machine-readable information; the current deken implentation really relies on the (non-)fact that humans and machines want to see the same information.
- writing a regex to match XML is crazy (it only works, because deken really parses a text-document that happens to look like XML, but has other properties as well)


last night i have cooked up an experimental (as in: URL and returned data are still subject to change) interface that queries the website for both IAEMfiles and software-releases  in an easier to parse way:

  http://puredata.info/dekenpackages?name=zexy

to get all packages omit the query string.

**Comment by chr15m** [comment]
:clap: :clap: :clap:

**Comment by danomatika** [comment]
JSON? I see there is a TCL only JSON parser: https://core.tcl.tk/tcllib/doc/trunk/embedded/www/tcllib/files/modules/json/json.html

**Comment by chr15m** [comment]
To use that the user would have to install a 3rd party TCL package. I want them to be able to just drop `deken-plugin.tcl` into their Pd externals directory and go.

**Comment by danomatika** [comment]
If it's just a single .tcl, it could included with the plugin.
