### ISSUE TITLE
Easywebdav and python3 compatibility

### ISSUE THREAD

**Issue by jpcima** [pure-data/deken#180]
I run deken on python3 which is default on my Linux setup. All the time, I run into this old bug. amnong/easywebdav#46
The fix is easy but seeing how unmaintained the easywebdav project is, it is not likely to receive new patches.
Can deken move to a fork which is well maintained? At first glance, there is easywebdav2 in pypi, it has received the python3 patches.

**Comment by umlaeute** [comment]
one problem with `easywebdav2` is that it is also broken (when it comes to [creating directories](https://github.com/zabuldon/easywebdav/pull/1))
