### ISSUE TITLE
Object finder not working 

### ISSUE THREAD

**Issue by electrickery** [pure-data/deken#183]
It appears the object finder functionality is no longer working which allowed finding objects in a library if a text file containing a list of object names was present in the deken package directory. The original design is described in "Object finder implementation #133".

Fonnd this after installing 0.3.1, but the old 0.2.4 that came with vanilla I tried afterwards doesn't work either.

**Comment by umlaeute** [comment]
the object finder functionality is actually implemented on the [server-side](https://git.iem.at/zmoelnig/deken-server) which seem to be broken...

**Comment by umlaeute** [comment]
fixed with https://git.iem.at/zmoelnig/deken-server/commit/35a5bb5a83f38788660f48805ce0edcb71617222
