### ISSUE TITLE
Deken preferences should have a vertical scrollbar for paths section

### ISSUE THREAD

**Issue by Jackovic** [pure-data/deken#184]
When you have too much paths in deken preferences, you can't see the end in the preferences window.

**Comment by umlaeute** [comment]
supposed to be fixed in current master (88675a94217dd4b80408374f0e992cdaee56ccd7...0bc9f2fabab2f5315809ae1e4db52a982ba3eaf0).

let me know if this works for you.

**Comment by Jackovic** [comment]
It works perfectly, thanx !
