### ISSUE TITLE
Deken 0.3.1 doesn't recognize its own source package

### ISSUE THREAD

**Issue by x37v** [pure-data/deken#186]
I have a clean checkout of my *jit_expr* source
I ran: `deken package -v 0.1 jit_expr/`

which created: 
  * `jit_expr[v0.1]()(Sources).dek`
  * `jit_expr[v0.1]()(Sources).dek.asc`
  * `jit_expr[v0.1]()(Sources).dek.sha256`

then I ran: `deken upload -v 0.1 jit_expr`

which gave the output:
```
Deken 0.3.1
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
Skipping 'jit_expr[v0.1]()(Sources).dek', it is not a valid deken package
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

Clearly I have an issue with this backend which I also need to figure out, but deken clearly doesn't see its source package as valid.

**Comment by umlaeute** [comment]
hmm, `()` is obviously an illegal architecture specification.
luckily `upload` refuses to upload.
