### ISSUE TITLE
0.3.1 complains about backend

### ISSUE THREAD

**Issue by x37v** [pure-data/deken#187]
After a fresh install of deken I tried to upload my package and saw this warning:

```
deken upload -v 0.1 jit_expr
Deken 0.3.1
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

I'm not sure if that is something I need to configure on my end or something in the deken software. If it is something I need to do on my end then I figure there should be notes about it in the developer README?

**Comment by umlaeute** [comment]
it's a warning about not being able to access a password manager ("keyring"). I'm not sure whether this can be turned off.

**Comment by x37v** [comment]
@umlaeute so is it safe to ignore? If so, I can add it to the deken developer README

**Comment by umlaeute** [comment]
yes it's safe to ignore.
