### ISSUE TITLE
Deken fails to create directories on server: Failed to create directory "<built-in function dir>".

### ISSUE THREAD

**Issue by x37v** [pure-data/deken#188]
My deken package upload fails to create directories that it needs. I've verified that I am using the correct login and password. After the first failure I created a *software* directory */Members/x37v/software/* but I got the same error after trying the package upload again.

I'm guessing deken should be able to create the subdirectories? If not, we should update the README to reflect the process.

Maybe something is mis-configured for my *puredata.info* account?
Maybe this is related to: https://github.com/pure-data/deken/issues/187

```
alex@lilbox:~/projects/jit_expr/build$ deken upload -v 0.1 --no-source-error jit_expr/
Deken 0.3.1
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
Please enter password for uploading as 'x37v': 
Failed to create directory "<built-in function dir>".
  Operation     :  MKCOL <built-in function dir>
  Expected code :  201 Created, 301 Moved Permanently, 405 Method Not Allowed
  Actual code   :  409 ConflictCouldn't upload to https://puredata.info/Members/x37v/software/jit_expr/0.1!
Are you sure you have the correct username and password set for 'https://puredata.info'?
Please ensure the folder '/Members/x37v/software/jit_expr/0.1' exists on the server and is writeable.
```

*writable* is also misspelled :smile:

**Comment by umlaeute** [comment]
thanks for the spelling correction :-)

about the actual error, it might be related to incorrect username/password settings (as mentioned) :-)
are you prompted for a password?
if not, try using `-P` (to force asking a password).

(and yes, `deken` *can* create directories under normal circumstances)

**Comment by x37v** [comment]
@umlaeute I just removed my password and username from my `~/.deken/config` file and tried the upload again, it asked me for my username "x37v" and my password, which I copied from my password manager and had just used on the *puredata.info* site, still no luck

```
alex@lilbox:~/projects/jit_expr/build$ deken upload --no-source-error -v 0.1 jit_expr
Deken 0.3.1
Environment variable DEKEN_USERNAME is not set and the config file /home/alex/.deken/config does not contain a 'username = ...' entry.
To avoid this prompt in future please add a setting to the config or environment.
Please enter username for https://puredata.info:: x37v
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
Please enter password for uploading as 'x37v': 
Failed to create directory "<built-in function dir>".
  Operation     :  MKCOL <built-in function dir>
  Expected code :  201 Created, 301 Moved Permanently, 405 Method Not Allowed
  Actual code   :  409 ConflictCouldn't upload to https://puredata.info/Members/x37v/software/jit_expr/0.1!
Are you sure you have the correct username and password set for 'https://puredata.info'?
Please ensure the folder '/Members/x37v/software/jit_expr/0.1' exists on the server and is writeable.
```

**Comment by x37v** [comment]
i just tried typing my password directly in case something happened with copy/paste but that didn't work either.

**Comment by umlaeute** [comment]
oh, i just remembered a problem that is likely to trigger your issue.

`deken` uses `easywebdav` to upload files (and create directories on the server).
Now `easywebdav` has a bug with Py3 (#180), which is why we use `easywebdav2` by default.
Unfortunately, `easywebdav2` is also somewhat buggy, when it comes to creating directories, see https://github.com/zabuldon/easywebdav/pull/1, which is most likely what you seeing).

See [developer/DEVELOPMENT.md](https://github.com/pure-data/deken/blob/master/developer/DEVELOPMENT.md) for a trivial fix for the problem.

in retrospect I think it is wrong to have `easywebdav2` in the `requirements.txt` (since i think most virtualenv installations will use Python2 which works nicely with `easywebdav`...)
esp. it uses `easywebdav2` because it is compatible with Python3 (#180), whereas the ori

**Comment by x37v** [comment]
@umlaeute great! that worked:
for others looking at this issue the file in question is in:
`.deken/virtualenv/lib/python2.7/site-packages/easywebdav2/client.py`
edit that, do do the fix here: https://github.com/pure-data/deken/blob/master/developer/DEVELOPMENT.md
and then I deleted `.deken/virtualenv/lib/python2.7/site-packages/easywebdav2/client.pyc` but i'm not sure if thats needed? I don't know python that well.
