### ISSUE TITLE
wrong architecture name armv6KZ

### ISSUE THREAD

**Issue by Ant1r** [pure-data/deken#195]
On rPi3/raspbian Jessie, Deken command line packager created a package with arch name `armv6KZ`, which is not recognized by Deken installer on the same platform. The package is installable though, it is shown if "hide foreign architecture" is unchecked.

```
uname -a:
Linux (...) 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

file bin/pof.l_arm:
bin/pof.l_arm: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=499d851b6e37f55938ad889e78ff90ce31090d66, not stripped

deken --version
0.4.1

Pd console: [deken]: installed version [0.2.4] < 0.4.1...overwriting!
```

**Comment by umlaeute** [comment]
could you please post the binary somewhere so i can test it (or send it privately to me)

**Comment by Ant1r** [comment]
The binary is available for regular deken download from:
http://puredata.info/Members/ant1r/software/pof/0.3-4-g4978/pof%5Bv0.3-4-g4978%5D%28Linux-armv6KZ-32%29.dek

**Comment by umlaeute** [comment]
thx. what is the platform detected by the deken-plugin (as the native one)

- Open `deken` (`Find externals...`)
- Open `Preferences`
- Check the value of `Default platform` in the `Platform settings` section (near the bottom)

**Comment by Ant1r** [comment]
I'm not with the machine now but IIRC it was armv6. Tomorrow I'll make sure.

**Comment by umlaeute** [comment]
in case you also own older raspberries (or other arm devices), would it be possible to provide the the following for all of these models as well:
- the `Default platform` (as reported by the deken preferences)
- a compiled external (the binary) that is known to work on this platform
   - the external should be compiled natively on the platform (not installed via some package manager)
   - it doesn't need to be `pof` (which is probably quite an overkill, something as trivial as an example from the externals-HOWTO would do)
   - no need to upload to deken/puredata.info

**Comment by Ant1r** [comment]
Deken plugin Default platform: `Linux-armv6l-32`
```
$ deken --platform
Linux-armv7l-32

```
- the rPi is not so old, it's a "Raspberry Pi3 model B v 1.2 2015"
- the pof I sent was compiled in this platform and runs well on it
- attached helloworld.pd_linux (compiled on the same system) runs well too (sorry github rejected .pd_linux extension so I had to zip it)


[helloworld.pd_linux.zip](https://github.com/pure-data/deken/files/2034411/helloworld.pd_linux.zip)

**Comment by umlaeute** [comment]
thanks for the additional info

about the older rpis: i was merely trying to collect additional data (just in case you have access to them)

**Comment by umlaeute** [comment]
btw, interesting that the `helloworld` is detected (by deken) as `armv7`, whereas the pof external is `armv6KZ`.
Just to be sure: both have been built on the same machine?
i guess that helloworld has been built using the pdlibbuilder Makefile, and pof uses it's own build system.
which compiler/linker flags are you using to build pof?

also, what is the `uname -a` output on the RPi3Bv1.2.2015?

**Comment by Ant1r** [comment]
Both have been built on the same machine. 
helloworld uses pdlibbuilder as configured on the github. 
pof uses openframeworks build system, which defines in the file:
 `openFrameworks/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk`:
```
PLATFORM_CFLAGS += -march=armv6
PLATFORM_CFLAGS += -mfpu=vfp
PLATFORM_CFLAGS += -mfloat-abi=hard
PLATFORM_CFLAGS += -fPIC
PLATFORM_CFLAGS += -ftree-vectorize
PLATFORM_CFLAGS += -Wno-psabi
PLATFORM_CFLAGS += -pipe

```
 and I added in the project's own config.make:
```
PROJECT_CFLAGS = -fPIC -DINCLUDE_VERSION_FILE
PROJECT_LDFLAGS = -rdynamic -shared -Wl,-rpath=./libs
```

As I said in the 1st post:
```
$ uname -a
Linux (...) 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
```

**Comment by umlaeute** [comment]
ah, i guess `-march=armv6` explains it. sorry about missing the *uname*.

**Comment by umlaeute** [comment]
@Ant1r could you confirm that the issue is fixed? if so, i'm going to put out another release

**Comment by Ant1r** [comment]
That's great; on the pi, the armv6KZ package does now appear on the list, and at the first place.
Many thanks!
