### ISSUE TITLE
"check" button not working

### ISSUE THREAD

**Issue by porres** [pure-data/deken#200]
This is either not working or I just don't get what it's for. Here's a screenshot

![screen shot 2018-08-06 at 15 59 23](https://user-images.githubusercontent.com/5360142/43735718-b78ff3d2-9991-11e8-95fd-66f013d89b8c.png)

So, above there's this "check" button, but it is not highlighted, and it is not clickable, so I don't know what it is for or what it is supposed to do. 

This is on macOS 10.12.6

**Comment by porres** [comment]
while we're at it, I don't see how downloading to doc/5.reference is a good/usable option

**Comment by umlaeute** [comment]
thanks for using "this" for a single unspecified item out of eight.

the directory is non-existing, and you can only select existing directories.
click on <kbd>Create</kbd> besides the disabled check-boxes (i see at least two of them), to (attempt to) create the directory. if that succeeded, you will be able to select the directory.

also note, that you might get disabled checkboxes for existing but non-writable directories. you can re-check the writable-state  with the <kbd>Check</kbd> button.

the UX could certainly be improved (i don't claim to be an expert here), but we are lacking tooltips and i really don't want to spend a long explanation inside the buttons.

i'll close this issue as i don't see a problem with the functionality per se.
if you have practical ideas for UX improvements, please don't hesitate to open an new issue (with screenshots or similar detailing an improvied UX)

**Comment by porres** [comment]
> you might get disabled checkboxes for existing but non-writable directories

weird, cause my folders in ~/Documents are clearly writable.

> i'll close this issue as i don't see a problem with the functionality per se.

I don't see a 'functionality' issue, I just don't understand why my check boxes are disabled, or even what they should do or what you mean by "re-check the writable-state "

**Comment by umlaeute** [comment]
i don't understand what your `~/Documents/` folder being writable has to do with the check-box for `/Library/Pd/` not being being selectable.
most likely i do not see the problem you are talking about in your screenshot (e.g. all the radio buttons that are somehow related to `~/Documents/` (1, 2, 7 & 8) seem to be perfectly selectable to my eye). please be more specific about your problem so i can understand it.

if it's unclear what the radio buttons are supposed to do, then we have a severe UX problem. (feel free to suggest concrete solutions in a new issue).

i really don't have the energy to explain what "re-check the writable-state" might mean in the context of "non-writable directories", maybe someone else could come up with an explanation.

**Comment by porres** [comment]
> i don't understand what your ~/Documents/ folder being writable has to do with the check-box for /Library/Pd/ not being being selectable.

Oh, nothing really, I dom't have any issues with the [create] buttons, I see how they work, they do create the folder, and then the button changes to [check]


> most likely i do not see the problem you are talking about in your screenshot (e.g. all the radio buttons that are somehow related to ~/Documents/ (1, 2, 7 & 8) seem to be perfectly selectable to my eye). please be more specific about your problem so i can understand it.

This is my problem, all [check] buttons don't do anything, I can't even click them, they are all disabled.

**Comment by porres** [comment]
you can see visually in the screenshot because they are not highlighted as the [create] button

**Comment by umlaeute** [comment]
so you are talking about the buttons with the <kbd>Check</kbd> labels? i was pretty confident that you were taking about [check buttons](https://en.wikipedia.org/wiki/Checkbox), confusing the term and actually meaning [radio buttons](https://en.wikipedia.org/wiki/Radio_button).
hence my repeated request to clarify what you mean.

The buttons labeled <kbd>Check</kbd> are disabled because there is nothing to check (the directories exist and are writable). If a directory existed without being writable by the user (e.g. `/Library/Pd/`), the button would be enabled to check (hence the name!) the directory permissions again after the administrator has fixed them.
