### ISSUE TITLE
mac format not specified

### ISSUE THREAD

**Issue by porres** [pure-data/deken#205]
Hi, I just uploaded an update of my library but for mac the package doesn't specify the platform for mac.

Here's a screenshot.

<img width="667" alt="screen shot 2019-02-04 at 14 37 26" src="https://user-images.githubusercontent.com/5360142/52222329-6cf36880-288a-11e9-809e-ecb98eed99b4.png">

It shows up as a highlighted option, it downloads and works just fine, but it only has the library name and version: **else[v1.0beta16].dek**

This never happened to me before, I can't see why this happened now. For all other platforms the packaging worked correctly as you can see in the screenshot as well!

cheers

**Comment by porres** [comment]
btw, can i just manually edit the file name?

**Comment by umlaeute** [comment]
to answer your last two questions: yes and yes.

however, the interesting part is why you got that weird package name (without the archs) in the first place.
any error messages (or warnings) you got when running `deken package`?

**Comment by umlaeute** [comment]
btw, the problem is that stray `fdn.rev~.pd_darwin` file that is lurking in the package.
what is it for?

**Comment by porres** [comment]
> btw, the problem is that stray fdn.rev~.pd_darwin file that is lurking in the package.
> what is it for?

geez, damn... that one shouldn't be there! It's not part of the package as it doesn't really exist yet :) 

Ok, so that's a bug I need to take care of, thanks!

**Comment by porres** [comment]
wait... I deleted that binary and it all still happens... 

No errors are given by deken, here's a screenshot

<img width="813" alt="screen shot 2019-02-04 at 17 18 54" src="https://user-images.githubusercontent.com/5360142/52231449-23624800-28a1-11e9-8ed2-295447560eb6.png">

**Comment by umlaeute** [comment]
ii don't think you can run `./deken` from a local checkout. it will most likely not do what you expect.

instead, you should upgrade you local installation:

~~~sh
$ deken upgrade
$ deken package -v 1.0beta16 else
~~~

**Comment by porres** [comment]
> i don't think you can run ./deken from a local checkout.

what is a "local checkout"?

I'm running ./deken from the "developer" folder inside the "deken" folder, and there is where I put the library folder to be packaged and uploaded.

 > instead, you should upgrade you local installation:

Hmm, I had just git cloned from the latest source this weekend, kinda sure I had the last version. But I did upgrade and stuff happened. Then I tried it again and still got the same result :/ 

<img width="1653" alt="screen shot 2019-02-04 at 18 55 36" src="https://user-images.githubusercontent.com/5360142/52236806-fcab0e00-28ae-11e9-8b30-a0208da19a23.png">

**Comment by umlaeute** [comment]
On 2/4/19 10:00 PM, Alexandre Torres Porres wrote:
> what is a "local checkout"?
> 
> I'm running ./deken from the "developer" folder inside the "deken" folder,

and

> Hmm, I had just git cloned from the latest source this weekend

*that* is a local checkout.

**Comment by porres** [comment]
ok, so I'm not running at local anymore because I upgraded, right? But I still get the same issue over and over...

**Comment by Ant1r** [comment]
I think you should copy your `deken` executable to `~/bin/` and execute this one: `~/bin/deken`.
It seems currently your `deken` is disturbed by the other files which are in the same directory (like `.hy` or `.py` ones).

**Comment by porres** [comment]
not sure if this is what you meant, but this is what I did:

- completely removed and started over, by cloning and upgrading: same result
- tried using another folder "bin" without any other files: same result

<img width="503" alt="screen shot 2019-02-04 at 20 36 17" src="https://user-images.githubusercontent.com/5360142/52242068-a775f900-28bc-11e9-8900-f5fb44d32738.png">

Note that this worked for all other platforms... just when packaging mac files is that this happens...

**Comment by porres** [comment]
so, should we reopen this?

**Comment by umlaeute** [comment]
you should first follow the instructions of @Ant1r .

or the [README](https://github.com/pure-data/deken/blob/master/developer/README.md) for that matter, which is really the same thing.

**Comment by porres** [comment]
well, I tried the instructions by @Ant1r  as I could understand it. I didn't have a ~/bin folder, so I created it somewhere else.

Now, by following the readme, I tried creating a ~/bin folder and used the commands from there.

$ curl https://raw.githubusercontent.com/pure-data/deken/master/developer/deken > ~/bin/deken
$ chmod 755 ~/bin/deken
$ deken

the last one did not tell me it was the first time it was running deken, it just complained there were too few arguments. So I tried packaging it and got the same thing.

<img width="986" alt="screen shot 2019-02-04 at 21 02 08" src="https://user-images.githubusercontent.com/5360142/52243419-b3fc5080-28c0-11e9-93b8-08286544caad.png">

Doing a further upgrade and retry gave me the same thing as well.

I do have a new computer with a new operating system (Mojave), so this is what changed from last time I did things my way (which worked just fine).

**Comment by umlaeute** [comment]
you are still running `./deken` which will most decidedly not execute the correct `deken` script you just installed.

**Comment by Ant1r** [comment]
run` ~/bin/deken` instead.

**Comment by Ant1r** [comment]
Your shell is not in the folder containing the directory `else`, so deken cannot find it.

You shouldn't have moved your `else` directory to `~/bin`, only the `deken` executable. The `else` directory could be located anywhere (let's say in ~/Documents), then in your shell go to this containing directory and execute deken:
```
$ cd ~/Documents
$ ~/bin/deken package -v 1.0beta16 else

```

**Comment by umlaeute** [comment]
fixed in git. please upgrade again.

**Comment by porres** [comment]
ok, upgraded and tested it, now I get this, which is way more than before and quite likely not necessary 

<img width="928" alt="screen shot 2019-02-05 at 21 43 56" src="https://user-images.githubusercontent.com/5360142/52311767-44a16200-298f-11e9-9970-f75b52f5d3e7.png">

I tested in the same way as last time, following instructions by @Ant1r , but later I also tested and got this same thing when doing it the old way that I was doing it...

**Comment by umlaeute** [comment]
you probably want to remove the stray `stray fdn.rev~.pd_darwin` again.

**Comment by porres** [comment]
Great, thanks!
