### ISSUE TITLE
Successful installation should be reported in the state panel at the bottom of the window

### ISSUE THREAD

**Issue by musger** [pure-data/deken#215]
just having used the Deken external installer on Linux and Win7 and it                                                 
seems to not post a "finished" or "success" message apart from a                                                       
completed progress bar leaving the user in an ambiguous situation.

Note that Deken currently posts something to Pd console in log level 3.

**Comment by umlaeute** [comment]
"something" being
> [deken] Successfully unzipped <dekfile> into <targetdir>.

with `<dekfile>` being the full filename of the deken (e.g. `zexy[v2.2.8](Windows-amd64-32).dek`).
And `<targetdir>` being the destination directory
