### ISSUE TITLE
Unable to modify default install directory under Windows

### ISSUE THREAD

**Issue by dfkettle** [pure-data/deken#219]
Hi!

When I go into "Find externals", then click on "Preferences", I'm unable to change the install directory. If I choose "C:/Program Files (x86)/Pd/extra" (in the 32-bit version of PureData), I get the error below. Likewise, if I choose "C:/Program Files/Pd/extra" (in the 64-bit version of PureData)", I get a similar error. I have both flavours of PureData v0.50.0 (32- and 64-bit) installed under Windows 7 HP, Service Pack 1, on a 64-bit desktop computer. I believe this is a bug in Deken, but I'm not sure. 

![Screenshot 2019-12-27 16 29 00](https://user-images.githubusercontent.com/8409615/71533595-9a446d00-28c7-11ea-8e4b-c8196b7a922d.png)

**Comment by umlaeute** [comment]
indeed.

could you try to manually install `deken` from this repository, and see whether the problem persists?

**Comment by umlaeute** [comment]
ah i forgot: the problem most likely originates from the spaces in the path.

(and: Windows7? isn't this unsupported by microsoft nowadays ;-))

**Comment by Spacechild1** [comment]
> (and: Windows7? isn't this unsupported by microsoft nowadays ;-))

Pd still has the requirement to work on Windows XP and OSX 10.6 ;-)

**Comment by dfkettle** [comment]
Yes, Windows 7 is no longer supported by Microsoft, that's true, but there are still a lot of people using it, including users of PureData. I don't think my current hardware would support later versions of Windows, and I see no benefit to upgrading. 

Do you still want me to install the latest version of Deken, or is it because of the spaces in the path? PureData itself is installed under "C:\Program Files (x86)", and it works fine. So I don't think it's unreasonable to expect Deken to also support spaces in the path. And as you can see from the screen capture, it even offers to do so.

![Screenshot 2019-12-27 20 10 19](https://user-images.githubusercontent.com/8409615/71537092-08e3f380-28e5-11ea-996b-16ae8711c348.png)

**Comment by dfkettle** [comment]
I think you're right about the spaces. I was able to install to a different folder that had no spaces in the path. But it still seems rather confusing to offer the user the option of installing in "C:\Program Files (x86)\Pd\extra" if it isn't going to work.

**Comment by Spacechild1** [comment]
I think we all agree that this is a bug.

> I don't think it's a Windows 7 issue.

Nobody argued that. The comment about Windows 7 was just a snide remark. (No worries, I'm still using Windows 7 myself :-)

**Comment by dfkettle** [comment]
Maybe you can answer a question for me. I'm not really clear on exactly what Deken does. Does it just download the library and unpack it into the folder you specify, or does it do something more than that? The reason I ask is that I was thinking I could just install the externals into a folder without any spaces in the path, then copy the contents into the folder I want (the one with the spaces). Under Windows, the default externals that come with Pure Data get installed in "C:/Program Files (x86)/Pd/extra" (32-bit) or "C:/Program Files/Pd/extra" (64-bit). Just for the sake of my own sanity and to make it easier to find things, I want to install any additional libraries in the same folder, so they'd all be in one place. Will it work if I just copy the sub-folders over, or is there some other piece of the puzzle I'm not aware of?

**Comment by umlaeute** [comment]
(for now,) `deken` only downloads and unpacks the package archives.
so you could indeed just copy the contents over.

the last release of deken in this repo (not yet included into mainline Pd), allows you to specify the placeholder `@PD_PATH@` which will expand to the full path of the running Pd instance (`C:/Program Files (x86)/Pd/extra`, or `C:/Program Files/Pd/extra`), which i think is exactly what you want...

**Comment by umlaeute** [comment]
afaict, this is fixed in current `deken` (not included yet with Pd)
