### ISSUE TITLE
deken upload crashes at line 248 if deken.hy

### ISSUE THREAD

**Issue by mrpeach-xx** [pure-data/deken#221]
Starting with Python 3, raw_input() was renamed to input()

**Comment by mrpeach-xx** [comment]
Sorry was using installed version of deken rather than the new one.

**Comment by umlaeute** [comment]
out of interest: which "installed" version (and *how* was it installed) on which OS?

**Comment by mrpeach-xx** [comment]
I seem to have deken 0.2.6 installed on ubuntustudio with  debian buster/sid. 
deken/bionic,bionic,now 0.2.6-1 all [installed]
pd-deken/bionic,bionic,now 0.2.6-1 all [installed]
pd-deken-apt/bionic,bionic,now 0.2.6-1 all [installed,automatic]

I probably installed it a while back and forgot about it.
