### ISSUE TITLE
request: bundle pack

### ISSUE THREAD

**Issue by porres** [pure-data/deken#222]
I wonder if there's a way to package two folders at once into a single deken package, that you can download and then decompress to two folders (or more, if you want to make a bundle of more than two folders).

I can understand this might be rather unusual or more of an edge case. In my use case, I was hoping to ship as a single download both my ELSE library and my Tutorial that depends on it.

But another use case could be someone packaging something like all of the Pd Extended libraries at once... or maybe a project with some third party dependency libraries, like jmmmp's library that depends on cyclone and others.

I guess something like that has already been requested?

**Comment by umlaeute** [comment]
first: a couple of things will not work as expected (e.g. the `try to remove libraries before (re)installing them` option of the deken-plugin (aka: the Pd side of things) will not be able to perform it's task, which might lead to problems (e.g. because the versions cyclone that comes with jmmmp will still see some cruft of the previously installed version).

second: you can do that, if you build the packages manually (after all, they are just ZIP-files with a special extension and a naming-convention)

i think that this is enough of an edge case, to not warrant a separate option in the `deken` cmdline tool.

finally: #122

**Comment by porres** [comment]
> second: you can do that, if you build the packages manually (after all, they are just ZIP-files with a special extension and a naming-convention)

Wow, I see... I'll try that for the next release, thanks

**Comment by porres** [comment]
> you can do that, if you build the packages manually (after all, they are just ZIP-files with a special extension and a naming-convention)

So, I'm trying this. I have a zipped file containing both folders in separate, I built it manually as a zip file and just changed the extension to .dek

when trying to upload, I get:

`Unable to process 'else_and_live_electronics_tutorial[v1.0beta28](Darwin-amd64-32).dek'!`

What am I missing?

thanks

**Comment by porres** [comment]
I'm doing this in macos, and if I change the generated package from deken by just typing a new extension (.zip instead of .dek), I get the icon of the default software for unpacking zip files in the file and I can unzip it just fine.

So all I did was get the .zip file and rename to .dek (this makes the icon of the software still appear)... 

So I have this

![Screen Shot 2020-06-06 at 16 23 14](https://user-images.githubusercontent.com/5360142/83952823-0d0c2980-a812-11ea-843f-df106c1b399f.png)

and it can't really upload it

**Comment by porres** [comment]
maybe there could be a better way to rename this to .dek? Maybe deken is still recognizing this as a .zip file, I dunno

**Comment by umlaeute** [comment]
why shouldn't it recognize the file as a ZIP-file? after all, it *is* a zipfile.
i guess the problem is something else.

run deken with `--verbose` (it might be worth trying to add the flag multiple times to increase verbosity), and *paste* the output of the terminal. (please do not add screenshots of the terminal)

**Comment by porres** [comment]
what I'm doing now is I packaged both folders inside another folder with deken and renamed it before uploading, this is happening, I'm not sure what I'll get when downloading from deken Let's see!

**Comment by porres** [comment]
> run deken with --verbose 

I did try 

`deken --verbose upload "else_and_live_electronics_tutorial[v1.0beta28](Darwin-amd64-32).dek" --no-source-error`

and still just got 

`Unable to process 'else_and_live_electronics_tutorial[v1.0beta28](Darwin-amd64-32).dek'!`

**Comment by porres** [comment]
>  I'm not sure what I'll get when downloading from deken Let's see!

It'll take some time until it is online, but I'm assuming I'll get a folder with two folders inside, which is not what I really wanted. My idea of a combo download was to get two separate folders from the unpacking/unziping. But anyway, I can't seem to upload the thing if I zip two separate folders and rename it, and --verbose is not helping. 

Have you tried this before? In All OSes? If you only did this in linux (I think you use mostly linux), maybe if I follow your steps in Linux I can get it working?

**Comment by umlaeute** [comment]
you only get the "Unable to process" error, if `deken` cannot find the file.

**Comment by porres** [comment]
Then I'm suspecting that even though I'm renaming the extension in macOS' finder, it still keeps an original and hidden .zip extension in the name and deken can't find it... I'll look into a maybe better and more efficient way to rename this thing in this OS! 

thanks!

**Comment by umlaeute** [comment]
how about the cmdline?

**Comment by porres** [comment]
well, I was able to do it in a different way and now it's uploaded, let's see if it does what I hope ot does when downloading from Pd, fingers crossed!

**Comment by porres** [comment]
> fingers crossed!

it was painful and long but it worked! I had to learn how to als remove bogus __MACOSX files form the zip package, yikes

Thanks!

**Comment by umlaeute** [comment]
sidenote, before you get all too crazy about being able to bundle:

- using bundles will **disable** the ability of deken to "uninstall before (re)installation".
the impliciation is, that the users may end up with old cruft after installing multiple versions of the bundle.
e.g. you have a library "frobnozzel" that contains a file "flabber.pd". you create a bundle "BMG[v1.0]" that contains the "frobnozzel[v0.2]" library (and therefore the "frobnozzel/flabber.pd" file). user sophie installs "BMG[v1.0]".
now you decide that "flabber.pd" is totally broken, and therefore you replace it with with "gobblefunk.pd" for "frobnozzel[v0.2.1]". the next version of the "BMG[v2.0]" bundle contains "frobnozzel/gobblefunk.pd" but no ~~"frobnozzel/flabber.pd"~~.
when sophie updates to "BMG[v2.0]" she will now have both "frobnozzel/gobblefunk.pd" **and** "frobnozzel/flabber.pd".
potentially creating confusion.
if there's a separate download for "frobnozzel[v0.2.1]" and sophie decides to install that, the "frobnozzel/flabber.pd" file will be gone.
potentially creating more confusion.

i think this not solvable with the current (simple) format for deken packages.
everything else would require something like `MANIFEST` files (on the package side) and a (smallish) database (on the Pd-side) that keeps track of what is installed by what.
i don't want to go that road, as there are already much better systems that provide them (e.g. `apt` on Debian-based distros).
