### ISSUE TITLE
problem installing deken cmdline on macOS

### ISSUE THREAD

**Issue by Ant1r** [pure-data/deken#223]
After downloading deken, first run installs dependencies, then fails. Subsequent run of deken fails as well.
OS: macOS 10.13.4 (17E199)
Python 3.8.5 (installed from brew)

-------

Macintosh:~ developpement$ deken
This is your first time running deken on this machine.
I'm going to install myself and my dependencies into /Users/developpement/.deken now.
Feel free to Ctrl-C now if you don't want to do this.
Installing deken.
Fetching Python requirements file: https://raw.githubusercontent.com/pure-data/deken/master/developer/requirements.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   171  100   171    0     0    194      0 --:--:-- --:--:-- --:--:--   194
Fetching main hylang file: https://raw.githubusercontent.com/pure-data/deken/master/developer/deken.hy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82854  100 82854    0     0   110k      0 --:--:-- --:--:-- --:--:--  110k
Downloading & installing Virtualenv.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0     72      0  0:00:01  0:00:01 --:--:--    72
100   281  100   281    0     0    145      0  0:00:01  0:00:01 --:--:--   145
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100 1924k  100 1924k    0     0   274k      0  0:00:07  0:00:07 --:--:--  600k
x virtualenv-16.0.0/
x virtualenv-16.0.0/PKG-INFO
x virtualenv-16.0.0/virtualenv_embedded/
x virtualenv-16.0.0/virtualenv_embedded/activate.bat
x virtualenv-16.0.0/virtualenv_embedded/activate.ps1
x virtualenv-16.0.0/virtualenv_embedded/activate.fish
x virtualenv-16.0.0/virtualenv_embedded/activate.sh
x virtualenv-16.0.0/virtualenv_embedded/python-config
x virtualenv-16.0.0/virtualenv_embedded/activate_this.py
x virtualenv-16.0.0/virtualenv_embedded/site.py
x virtualenv-16.0.0/virtualenv_embedded/distutils-init.py
x virtualenv-16.0.0/virtualenv_embedded/distutils.cfg
x virtualenv-16.0.0/virtualenv_embedded/deactivate.bat
x virtualenv-16.0.0/virtualenv_embedded/activate.csh
x virtualenv-16.0.0/bin/
x virtualenv-16.0.0/bin/rebuild-script.py
x virtualenv-16.0.0/tests/
x virtualenv-16.0.0/tests/test_virtualenv.py
x virtualenv-16.0.0/tests/test_activate.sh
x virtualenv-16.0.0/tests/test_activate_output.expected
x virtualenv-16.0.0/tests/__init__.py
x virtualenv-16.0.0/tests/test_cmdline.py
x virtualenv-16.0.0/MANIFEST.in
x virtualenv-16.0.0/virtualenv.egg-info/
x virtualenv-16.0.0/virtualenv.egg-info/PKG-INFO
x virtualenv-16.0.0/virtualenv.egg-info/not-zip-safe
x virtualenv-16.0.0/virtualenv.egg-info/SOURCES.txt
x virtualenv-16.0.0/virtualenv.egg-info/entry_points.txt
x virtualenv-16.0.0/virtualenv.egg-info/top_level.txt
x virtualenv-16.0.0/virtualenv.egg-info/dependency_links.txt
x virtualenv-16.0.0/docs/
x virtualenv-16.0.0/docs/index.rst
x virtualenv-16.0.0/docs/reference.rst
x virtualenv-16.0.0/docs/Makefile
x virtualenv-16.0.0/docs/conf.py
x virtualenv-16.0.0/docs/development.rst
x virtualenv-16.0.0/docs/make.bat
x virtualenv-16.0.0/docs/installation.rst
x virtualenv-16.0.0/docs/userguide.rst
x virtualenv-16.0.0/docs/changes.rst
x virtualenv-16.0.0/setup.py
x virtualenv-16.0.0/scripts/
x virtualenv-16.0.0/scripts/virtualenv
x virtualenv-16.0.0/setup.cfg
x virtualenv-16.0.0/virtualenv_support/
x virtualenv-16.0.0/virtualenv_support/wheel-0.31.1-py2.py3-none-any.whl
x virtualenv-16.0.0/virtualenv_support/setuptools-39.1.0-py2.py3-none-any.whl
x virtualenv-16.0.0/virtualenv_support/__init__.py
x virtualenv-16.0.0/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl
x virtualenv-16.0.0/README.rst
x virtualenv-16.0.0/LICENSE.txt
x virtualenv-16.0.0/AUTHORS.txt
x virtualenv-16.0.0/virtualenv.py
running build
running build_py
creating build
creating build/lib
copying virtualenv.py -> build/lib
creating build/lib/virtualenv_support
copying virtualenv_support/__init__.py -> build/lib/virtualenv_support
copying virtualenv_support/pip-10.0.1-py2.py3-none-any.whl -> build/lib/virtualenv_support
copying virtualenv_support/setuptools-39.1.0-py2.py3-none-any.whl -> build/lib/virtualenv_support
copying virtualenv_support/wheel-0.31.1-py2.py3-none-any.whl -> build/lib/virtualenv_support
Setting up the virtual environment.
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8'
/Users/developpement/.deken/virtualenv-source/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /Users/developpement/.deken/virtualenv/bin/python3.8
Also creating executable in /Users/developpement/.deken/virtualenv/bin/python
Installing setuptools, pip, wheel...done.
Installing deken library dependencies.
Collecting hy==0.17.0
  Downloading hy-0.17.0-py2.py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 360 kB/s 
Collecting easywebdav2==1.3.0
  Downloading easywebdav2-1.3.0-py2.py3-none-any.whl (5.1 kB)
Collecting pyelftools==0.25
  Downloading pyelftools-0.25-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 399 kB/s 
Collecting macholib==1.11
  Downloading macholib-1.11-py2.py3-none-any.whl (36 kB)
Collecting pefile==2019.4.18
  Downloading pefile-2019.4.18.tar.gz (62 kB)
     |████████████████████████████████| 62 kB 349 kB/s 
Collecting python-gnupg==0.4.5
  Downloading python_gnupg-0.4.5-py2.py3-none-any.whl (16 kB)
WARNING: Installing from a newer Wheel-Version (1.1)
Collecting keyring==18.0.1
  Downloading keyring-18.0.1-py2.py3-none-any.whl (35 kB)
Collecting ndg_httpsclient==0.5.1
  Downloading ndg_httpsclient-0.5.1-py3-none-any.whl (34 kB)
Collecting pyasn1==0.4.2
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 523 kB/s 
Collecting pyopenssl==19.0.0
  Downloading pyOpenSSL-19.0.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 396 kB/s 
Collecting astor>=0.8
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting rply>=0.7.7
  Downloading rply-0.7.7-py2.py3-none-any.whl (15 kB)
Collecting funcparserlib>=0.3.6
  Downloading funcparserlib-0.3.6.tar.gz (30 kB)
Collecting clint>=0.4
  Downloading clint-0.5.1.tar.gz (29 kB)
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 280 kB/s 
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting altgraph>=0.15
  Downloading altgraph-0.17-py2.py3-none-any.whl (21 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 602 kB/s 
Collecting entrypoints
  Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting cryptography>=2.3
  Downloading cryptography-3.0-cp35-abi3-macosx_10_10_x86_64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 484 kB/s 
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting args
  Downloading args-0.1.0.tar.gz (3.0 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 617 kB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 620 kB/s 
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 392 kB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 530 kB/s 
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.2-cp38-cp38-macosx_10_9_x86_64.whl (176 kB)
     |████████████████████████████████| 176 kB 409 kB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 578 kB/s 
Building wheels for collected packages: pefile, funcparserlib, clint, future, args
  Building wheel for pefile (setup.py) ... done
  Created wheel for pefile: filename=pefile-2019.4.18-py3-none-any.whl size=60821 sha256=892c5932c8e266b2bffd5ef50db0c2e4d08888b2ef2814b1c653a2d6551d8ba4
  Stored in directory: /Users/developpement/Library/Caches/pip/wheels/42/52/d5/9550bbfb9eeceaf0f19db1cf651cc8ba41d3bcf8b4d20e4279
  Building wheel for funcparserlib (setup.py) ... done
  Created wheel for funcparserlib: filename=funcparserlib-0.3.6-py3-none-any.whl size=17449 sha256=8372904d33ad05008ea238d23cb4618c7db9a8c29115fc77c53f52964c47b618
  Stored in directory: /Users/developpement/Library/Caches/pip/wheels/70/b9/5f/5e31319e22a04c60a85f0939ecb69c5da26dc3b37fff8ec3c8
  Building wheel for clint (setup.py) ... done
  Created wheel for clint: filename=clint-0.5.1-py3-none-any.whl size=34446 sha256=68dd5ccec5042e0b057e3e7dd798365eca8f4a85e1498eec56a225366124e82f
  Stored in directory: /Users/developpement/Library/Caches/pip/wheels/84/c4/6d/3235262e25e25ce8f080be07d9181853c92e0be64bb1a5d219
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=6a686d3eb2598d203aef32d07b6b104550261b72c09fec5e9c170f0e7aef9a9b
  Stored in directory: /Users/developpement/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for args (setup.py) ... done
  Created wheel for args: filename=args-0.1.0-py3-none-any.whl size=3316 sha256=39c877e448258c8ed72d070917cd07060f58c36284533841fb326032b88bd36f
  Stored in directory: /Users/developpement/Library/Caches/pip/wheels/08/5b/6a/d4c08f9d355023389016ed57db4099cf7091627fd5de717da6
Successfully built pefile funcparserlib clint future args
WARNING: Installing from a newer Wheel-Version (1.1)
Installing collected packages: astor, appdirs, rply, funcparserlib, args, clint, hy, urllib3, certifi, chardet, idna, requests, six, easywebdav2, pyelftools, altgraph, macholib, future, pefile, python-gnupg, entrypoints, keyring, pyasn1, pycparser, cffi, cryptography, pyopenssl, ndg-httpsclient
  WARNING: Installing from a newer Wheel-Version (1.1)
  WARNING: Installing from a newer Wheel-Version (1.1)
Successfully installed altgraph-0.17 appdirs-1.4.4 args-0.1.0 astor-0.8.1 certifi-2020.6.20 cffi-1.14.2 chardet-3.0.4 clint-0.5.1 cryptography-3.0 easywebdav2-1.3.0 entrypoints-0.3 funcparserlib-0.3.6 future-0.18.2 hy-0.17.0 idna-2.10 keyring-18.0.1 macholib-1.11 ndg-httpsclient-0.5.1 pefile-2019.4.18 pyasn1-0.4.2 pycparser-2.20 pyelftools-0.25 pyopenssl-19.0.0 python-gnupg-0.4.5 requests-2.24.0 rply-0.7.7 six-1.15.0 urllib3-1.25.10
Traceback (most recent call last):
  File "/Users/developpement/.deken/virtualenv/bin/hy", line 5, in <module>
    from hy.cmdline import hy_main
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/cmdline.py", line 358, in <module>
    def koan_macro(ETname):
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/macros.py", line 55, in _
    fn = rename_function(fn, name)
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/_compat.py", line 69, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
TypeError: an integer is required (got type bytes)
Macintosh:~ developpement$ ~/bin/deken 
Traceback (most recent call last):
  File "/Users/developpement/.deken/virtualenv/bin/hy", line 5, in <module>
    from hy.cmdline import hy_main
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/cmdline.py", line 358, in <module>
    def koan_macro(ETname):
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/macros.py", line 55, in _
    fn = rename_function(fn, name)
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/_compat.py", line 69, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
TypeError: an integer is required (got type bytes)

----------

Macintosh:~ developpement$ deken
Traceback (most recent call last):
  File "/Users/developpement/.deken/virtualenv/bin/hy", line 5, in <module>
    from hy.cmdline import hy_main
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/cmdline.py", line 358, in <module>
    def koan_macro(ETname):
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/macros.py", line 55, in _
    fn = rename_function(fn, name)
  File "/Users/developpement/.deken/virtualenv/lib/python3.8/site-packages/hy/_compat.py", line 69, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
TypeError: an integer is required (got type bytes)

**Comment by umlaeute** [comment]
unfortunately i can reproduce this.

argh: `hy` is really nice, but it is changing so fast!

**Comment by umlaeute** [comment]
i think this is fixed now.
you have to fetch the latest [`deken` cmdline tool first](https://raw.githubusercontent.com/pure-data/deken/master/developer/deken) and run it again.

**Comment by Ant1r** [comment]
thanks a lot!
it works just fine now.
I also had to remove the previous ~/.deken directory first.
