### ISSUE TITLE
improve sorting

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#230]
right now, search results are sorted upside-down.
this has the benefit of sorting new releases of a library before old releases.

however, this has also the drawback that
- libraries appear in reverse alphabetic order (`zexy` sorts before `arraysort`)
- and it doesn't take release dates into account

i think the proper sorting would be:
- sort libraries by their newest release (library that has the newest release comes first)
- within a library, sort by release (highest first)

**Comment by electrickery** [comment]
This would be the closest to human logic as computer logic can get.
