### ISSUE TITLE
deken-plugin error on startup (windows)

### ISSUE THREAD

**Issue by oliverstotz** [pure-data/deken#236]
This is on Windows with PD 0.51.4 and deken-plugin 0.7.1 and the issue was reported by other users as well (Dario Pedrioli, Roman Haefeli)

When i install the newest "deken-plugin" (version 0.7.1) and restart PD, i get the following output on the PD console (error level 4)

~~~
Loading plugin: C:/Program Files/Pd/tcl/pd_deken.tcl
[deken]: platform detected: Windows-amd64-float32
Loading plugin: C:/Program Files/Pd/tcl/pd_docsdir.tcl
Loading plugin: C:/Program Files/Pd/extra/deken-plugin/deken-plugin.tcl
[deken] installed version [0.5.0] < 0.7.1...overwriting!
[deken] deken-plugin.tcl (Pd externals search) loaded from C:/Program Files/Pd/extra/deken-plugin.
[deken] Platform detected: Windows-amd64-float32-----------
UNHANDLED ERROR: char map list unbalanced
    while executing
"string map "@PD_PATH@ $::sys_libdir" $path"
    (procedure "::deken::utilities::substpath" line 2)
    invoked from within
"::deken::utilities::substpath $p "
    (procedure "::deken::utilities::get_writabledir" line 3)
    invoked from within
"::deken::utilities::get_writabledir [list $::deken::installpath ] "
    (procedure "::deken::find_installpath" line 5)
    invoked from within
"::deken::find_installpath"
    (procedure "::deken::initialize" line 10)
    invoked from within
"::deken::initialize"
    invoked from within
"if { [::deken::versioncheck 0.7.1] } {

namespace eval ::deken:: {
    namespace export open_searchui
    variable winid
    variable platform
    var..."
    ("uplevel" body line 100)
    invoked from within
"uplevel #0 $tclcode"
FAILED TO LOAD C:/Program Files/Pd/extra/deken-plugin/deken-plugin.tcl
-----------
Loading plugin: C:/Program Files/Pd/extra/dnd-plugin/dnd-plugin.tcl
~~~

i DO get the new "search for ..." options when i open the "find externals"
window (despite of the startup error), but deken now doesn't find ANYTHING.

so no matter if i type "zexy" or "demux" or "shell" i get no result whatsoever.

only removing the deken-plugin and restarting PD helps

**Comment by Lucarda** [comment]
@umlaeute this behavior happens on the properly installed Pd's. I mean those installed on: "C:\Program Files"
"C:\Program Files (x86)"

It does not happen if you run the zip version on another (writable?) folder, for example from :

"C:\Users\me\Downloads"

@oliverstotz can you confirm?

**Comment by oliverstotz** [comment]
yes, i can confirm !
it's working on my zipped PD version on my D:\ partition, where i don't have a space in the full path name. 

With the windows "official" installation (which will put PD into "C:\Program Files\" ---> so: a space in the full name) the error occurs 

so it seems to be a good old space-in-full-path issue

**Comment by Lucarda** [comment]
@oliverstotz  thanks :)

It can also be related that "`C:\Program Files\Pd`" is not writable. If you want to test for that go to your standard Pd installation folder and give it write permissions. (I didn't test this yet)

**Comment by oliverstotz** [comment]
No, that doesn't help (just tried it)

I'm pretty sure it's the space-in-full-name thing that's producing the error

**Comment by Lucarda** [comment]
>No, that doesn't help (just tried it)

Confirmed. This didn't work for me either.

>I'm pretty sure it's the space-in-full-name thing that's producing the error

Seems so.

:)

**Comment by umlaeute** [comment]
thanks a lot for the detailed bug-report.

i can reproduce this on linux if Pd lives in a folder with spaces, so we do have culprit (and it's lots easier to debug for me ;-))
