### ISSUE TITLE
Improve progress bar behavior

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/deken#241]
Ideally, a progress bar should only be shown *during* an operation, i.e. it should be hidden before an operation begins and after the operation completes.

More importantly, the progress bar should not stay at 100% after the operation has finished, because users might think that it's still running. (We all know those installers which take a few seconds for the first 99% and then stay for minutes on the last % - or don't finish at all :-)

I personally had to explain students that the installation has finished, even thought the progress bar is still green. This happened more than once.

**Comment by umlaeute** [comment]
better? (as seen in git)

**Comment by Spacechild1** [comment]
Yes :-)
