### ISSUE TITLE
"show newest only" hides valid results

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#244]
In deken-plugin 7.6, when "Only show the newest version of a library?" is checked, it seems some valid results are hidden. For instance, a search for 'osc' shows nothing on Linux-amd64-32 or Windows-amd64-32. When unchecking this box, results for matching architecture is shown.

**Comment by umlaeute** [comment]
bummer.
confirmed.

**Comment by umlaeute** [comment]
better?

**Comment by reduzent** [comment]
I confirm it is fixed. Cool! Thanks.
