### ISSUE TITLE
remove redundant question marks in deken-plugin preferences

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#245]
The sentences near checkboxes make as much sence without the question marks as with them. If they do not  add meaning, they could be removed as well. 

```
  [  ] Maybe it is a matter of personal preference?
```

**Comment by umlaeute** [comment]
if this is a real problem for you please provide a PR.

(or put otherwise: on *my* priority lists this is below)

**Comment by reduzent** [comment]
No, not a real problem, but also quite simple to fix. 

Check: https://github.com/pure-data/deken/pull/246

**Comment by umlaeute** [comment]
thanks.merged.
