### ISSUE TITLE
show a list of all available externals

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/deken#251]
I think it would be great if Deken and/or http://deken.puredata.info/ could show a list of all available externals. This would really help to enable discoverability.

Bonus point: the list would also contain the number of downloads, so that it can be sorted by popularity.

For example, this is SuperCollider's Quark interface:

![grafik](https://user-images.githubusercontent.com/16126632/141651771-d4897c26-be02-44f3-9767-00fa8120ac2e.png)

**Comment by Ant1r** [comment]
Both (pd dialog and website) already show all packages after an empty search, like:

https://deken.puredata.info/search.html?libraries=+&objects=

No popularity sorting though...

**Comment by Spacechild1** [comment]
True! In Deken, the search button even says "Show all"... d'oh... On the website it's less obvious, though. I think it should show the full list on page load.

Personally, I find the results of "Show all" in Deken a bit overwhelming and hard to navigate. If you show all versions, you just get a massive list. And it doesn't help that scrolling doesn't work :-)

The website is much nicer in this regard: you have a small section for each library containing the different versions. Also, it is sorted alphabetically. (Deken apparantely sorts by upload date). It could be nice to support other sorting mechanisms, e.g. most recent upload date, popularity, etc.

I think we could use the website as a means to get a nice overview of existing externals and then people can use Deken to actually download the ones they are interested in. See also https://github.com/pure-data/deken/issues/250.

**Comment by umlaeute** [comment]
> Another thing: if you click on one of the externals, it would open a new page (e.g. https://deken.puredata.info/search.html?libraries=acre). This could be a good opportunity to also show the object list, for example.

not really sure i understand.

`acre` is a bad example, as it doesn't have an objectlist.

but see [`zexy`](https://deken.puredata.info/search.html?libraries=zexy).
the object list is *per download*, because:
- for actively developed packages, the objectlist typically changes (grows) with releases
- for complicated packages, the objectlist might be different for different (system-specific) binaries of the same release


sidenote: there's also a server-specific issue tracker on https://git.iem.at/zmoelnig/deken-server/-/issues...

**Comment by giuliomoro** [comment]
It would also be useful to have a button to "download all packages on screen" or "all sources"

Workaround: a script to download all deken sources and uncompress them:
```
curl "http://deken.puredata.info/search.html?libraries=&objects=" | cat external-list | grep "(Sources).dek" | grep '"url"' | sed 's^.*value="\(http://.*\.dek\)".*^\1^' | xargs wget
for a in *.dek; do
	d=${a%.dek}
	echo $d
	mkdir -p $d
	cd $d
	tar xf ../$a
	cd -
done
```
notes:
- it relies on the package's URL to end with `(Sources).dek`.
- some packages seem to have several versions of `(Sources)` for a given version, e.g.:
```
iemgui[v1.21](Darwin-amd64-32)(Darwin-i386-32)(Linux-amd64-32)(Windows-amd64-32)(Windows-i386-32)(Sources)
iemgui[v1.21](Darwin-i386-32)(Sources)
iemgui[v1.21](Windows-amd64-32)(Windows-i386-32)(Sources)
iemgui[v1.21](Windows-i386-32)(Sources)
iemlib[v1.21](Darwin-i386-32)(Sources)
iemlib[v1.21](Windows-amd64-32)(Windows-i386-32)(Sources)
iemlib[v1.21](Windows-i386-32)(Sources)
```

**Comment by umlaeute** [comment]
@giuliomoro i think that's a completely different task, and should go into a separate ticket (if you really think you need this; i'm a bit doubtful)

**Comment by umlaeute** [comment]
and for what it is worth: i think @Spacechild1 's original suggestion should be split into two separate issues (one of the plugin, another for the webinterface (the latter either in the [`deken-server`](https://git.iem.at/zmoelnig/deken-server/-/issues) repository or here).

i think i'm going to remove the off-topic comments from this ticket here.

**Comment by umlaeute** [comment]
closing this.

- the plugin already says <kbd>Show All</kbd>
  - the webpage (although somewhat off-topic here), has also grown a <kbd>Show All</kbd> button.
- as of fd73653ffdd4bab9b7f2a18530461bb86014ec88 right-clicking on a result and selecting *Open package webpage* will take you to the relevant page on https://deken.puredata.info/
- the interface has been revamped to be sortable and collapsible, hopefully this will also help.
