### ISSUE TITLE
bug with "only show the newest version of a library"

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/deken#252]
If you enable "only show the newest version of a library" and search for "mrpeach", all results are greyed out. In case you have ticked "Hide foreign architectures", the results would be empty.

If I disable this option, I get the correct result (32-bit Pd on Windows 7): `mrpeach-v0.0.extended-(Windows-i386-32)-externals.zip`

First I thought it was a problem with the `v0.0.extended` version, but it does not happen with "unauthorized", for example.

**Comment by umlaeute** [comment]
What's the deken platform (as shown in the preferences)? and what does the "[deken] platform (re-)detected" show on the Pd-console when starting up?

**Comment by Spacechild1** [comment]
Sorry, I just realized I don't have the latest version. This bug doesn't occur anymore with v0.8!

**Comment by umlaeute** [comment]
right. i guess this was a dupe of #244
