### ISSUE TITLE
scroll wheel doesn't work

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/deken#253]
I can't use the mouse scroll wheel to scroll through the list of externals. This is especially painful when the list is very long, e.g. with "Show All".

Deken 0.8, Windows 7.

**Comment by umlaeute** [comment]
but you can at least drag the scrollbars?

**Comment by umlaeute** [comment]
and fun fact: it seems to only not work under windows.

**Comment by umlaeute** [comment]
@Spacechild1 could you try the latest and greatest plugin (directly from the repository)?

the scrollbars have now been removed, so if the scroll wheel still doesn't work your going to have a hard time (and I need to find a fix before releasing 0.9)

**Comment by Spacechild1** [comment]
Hi, the new layout with expandable items is just great! Scrolling also works fine. Also, the initial instructions in the "Log" window are very helpful.

Why did you remove the scroll bars? IMO, if something is scrollable, scrollbars should be present. Not only do they indicate that the widget is scrollable in the first place, it also shows the user the current scrolling position. For me, the absence of scrollbars is quite jarring.

**Comment by umlaeute** [comment]
mostly because the treeview widget already does the scrolling automatically (so: less code, less bugs).

cool that it works,

**Comment by umlaeute** [comment]
scrollbars have been (re)added with bab1d652e8c338842c770935ca9b54724b1a7c87.

i guess i can close this
(if the scrollbars magically disabled the scroll-wheel, please re-open)

**Comment by Ant1r** [comment]
thanks, the new layout is beautiful! And very convenient too.
