### ISSUE TITLE
Application error shows up if default directory does not exist

### ISSUE THREAD

**Issue by ritsch** [pure-data/deken#256]
It is not really am error, since normally no user is as paranoid as I am and deletes its shared library directory to get no false versions of libraries for a project with "rm -r ~/.local/lib/pd", but claims itself an error, so I report:

When installing a deken package via "Find External" dialog and not directory is chosen with "more->.."  the error dialog pops up:

```
Application Error:

couldn't open "/home/winfried/.local/lib/pd/extra/dekentmp.0": no such file or directory
couldn't open "/home/winfried/.local/lib/pd/extra/dekentmp.0": no such file or directory
    while executing
"open $downloadfilename w"
    (procedure "::deken::utilities::download_file" line 4)
![deken_config](https://user-images.githubusercontent.com/6206135/152955355-0d897a83-879c-4e6e-8abb-f6deca875757.png)
![deken_error](https://user-images.githubusercontent.com/6206135/152955390-27ce2383-4422-4b5f-9fd2-b9ab154ce990.png)

    invoked from within
"::deken::utilities::download_file $URL $fullpkgfile "::deken::download_progress""
    (procedure "::deken::clicked_link" line 16)
    invoked from within
"::deken::clicked_link {http://puredata.info/Members/ritsch/software/acre/1.0/acre[v1.03].dek} {acre[v1.03].dek}"
    (command bound to event)
```

- Why I detected the error:

This is with version 0.51.1 since in older version I advised others to download packages to project directory in a "libs" folder, to get independent of the current installation of packages in a specific account, like on stage, where I do not use my personal account with all my passwords... 

![deken_error](https://user-images.githubusercontent.com/6206135/152955556-11ffafc4-763a-4c45-8ccc-4405878d55d9.png)
![deken_config](https://user-images.githubusercontent.com/6206135/152955590-010908f8-951d-42df-8a0d-d07e4c344a90.png)

**Comment by umlaeute** [comment]
> It is not really an error, ...


it definitely *is* a real error.
thanks for reporting.

**Comment by umlaeute** [comment]
steps to reproduce:
1. remove¹ the `~/.local/lib/pd/extra/` directory
2. remove¹ the deken path settings, `~/.config/Pd/org.puredata.pd.pd-gui/dekenpath.conf`
3. Start Pd, open <kbd>Find Externals...</kbd>
4. search for any external and click to install it

**Comment by umlaeute** [comment]
i guess this is somewhat related  to https://github.com/pure-data/deken/issues/249
