### ISSUE TITLE
versions do not sort correctly

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#269]
e.g. `iemlib[1.22]` sorts before `iemlib[1.22-2]`

**Comment by Ant1r** [comment]
I don't see that here... iemlib[1.22-2] is listed before, on both Pd and web.

**Comment by umlaeute** [comment]
hmm. it's a bit weird: the version comparison seems to work fine, but not the sorting of libraries.
one side effect of this is, that if you have enabled "Only show the newest version of a library" then the `1.22-2` version will show on top (and `1.22` being marked as not-the-newest and shown greyed out).
this is because the version-check correctly marks `1.22-2` as the most recent and "matching" results are always sorted before "non-matching" results:

![sorted](https://user-images.githubusercontent.com/214034/168661323-622e3e7a-2bed-4fc7-ba05-b5af9e0558ba.png)

however, when disabling the "Only show the newest version of a library", then they are sorted wrongly:
![unsorted](https://user-images.githubusercontent.com/214034/168661477-e41b281d-e75e-4ce9-aea6-2e4062c8357b.png)

on https://deken.puredata.info/ sorting is done differently (and easier to get right)
