### ISSUE TITLE
Kick things off by packaging up the existing set of externals binaries from the last Pd extended auto-build

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#28]
http://autobuild.puredata.info/auto-build/2013-08-08/

**Comment by danomatika** [comment]
Sweet. 64 bit GEM + everything else!

**Comment by umlaeute** [comment]
mention #60

**Comment by umlaeute** [comment]
what would the version(s) for the externals be?

most likely all externals that are already uploaded by now, are more recent builds than the 2013-08-08 build, so these versions should sort before the Pd-extended ones.

i guess a dummy-version lke `0.0.20130808PdX:2.0.3` (with the `2.0.3` after the colon being the real version of the library) would be a good idea.

**Comment by chr15m** [comment]
I was just going to do `-v extended` and skip the libraries that have already been uploaded (zexy, cyclone, creb, etc.)

Really these are place-holders until something better/newer is uploaded. I was assuming a) there will be no more Pd-extended releases b) the extended externals we upload will be replaced with newer compiles so won't be there long. Maybe that's shortsighted though. The versioning you suggest seems a bit complicated to me - what about: `extended-20130808:2.0.3`? Hm, maybe that is a bike-shed suggestion.

Do you know if all externals in extended have valid version numbers?

**Comment by umlaeute** [comment]
i think that `extened-0.0` will sort before `32.1`, thus making the impression that it is newer.

since many externals don't have proper releases (that is, they are using `0. ...`), the simplest version should probably be `0.0.extended`

**Comment by chr15m** [comment]
Ok that sounds good.

**Comment by chr15m** [comment]
I did not realise you had implemented sort-by-version already.

**Comment by chr15m** [comment]
Ok wait, so we haven't implemented that. No problem, using the version you suggest for extended packages should be forwards-compatible for when we do.

**Comment by umlaeute** [comment]
did i?

in any case, the output *should* be sorted by version, so we should make sure that the versions are usable...

**Comment by chr15m** [comment]
#62 - sort by version first

**Comment by chr15m** [comment]
#62 is closed but this still depends on #63 because any script for automating the upload of these old externals is going to ask for a GPG passphrase many times.

**Comment by umlaeute** [comment]
in #63 is was mainly referring to the webdav authentication password.

for a possible solution for gpg-signing see #65 and `gpg-agent`

**Comment by chr15m** [comment]
I did not know about `gpg-agent`, will investigate, thanks.

**Comment by chr15m** [comment]
Calling this in the `extra` folder of each pd-extended zip.

```
#!/usr/bin/env bash
for x in `find ./ -maxdepth 1 -type d | grep -ve './$'`; do deken upload $x; done
```

**Comment by chr15m** [comment]
argggg i forgot to set the `--version` flag.

**Comment by umlaeute** [comment]
probably that one is better:

     find ./ -mindepth 1 -maxdepth 1 -type d -exec deken package \{\} \;
     find ./ -mindepth 1 -maxdepth 1 -type d -exec deken upload \{\} \;

**Comment by chr15m** [comment]
i got it working with this:
```
#!/usr/bin/env bash
for x in `find ./ -maxdepth 1 -type d | grep -ve './$'`; do deken upload --version 0.0.extended $x; done
```

I will have to finish up the other platforms tomorrow.

**Comment by umlaeute** [comment]
should we put all those externals into a special folder so it doesn't clutter the *normal* use of deken?

 e.g. `.../chr15m/software/extended-0.43.4-1/`

**Comment by chr15m** [comment]
Happy to do that, but I don't know what you mean by "*normal* use of deken", or how putting them in a subfolder would change anything.

**Comment by chr15m** [comment]
Oh, I see you uploaded the OSX ones - thanks! Do we need the Linux binaries up there? I guess so as not all are packaged in Debian.

**Comment by umlaeute** [comment]
With *normal use* i meant day-to-day use where you don't maintain ~60 packages. It just makes sense for me to organize things in folders...

**Comment by umlaeute** [comment]
(sorry for the assignment mess; kid on keyboard)

**Comment by chr15m** [comment]
Yep good idea, I should move those packages into a single folder in my home dir.

**Comment by chr15m** [comment]
Should I do the Linux packages as well for consistency?

**Comment by chr15m** [comment]
`for x in `find Pd-0.44.0-extended-20130808-i386/ -name '*.pd_linux'`; do mv $x ${x/.pd_linux/.l_i386}; done;`

`for x in `find Pd-0.44.0-extended-20130808-i386/ -name '*.l_i386'`; do cp ${x} ${x/-i386/-amd64}; done;`

**Comment by chr15m** [comment]
Imperfect, but basically done.
