### ISSUE TITLE
trouble using 'deken install' on m1

### ISSUE THREAD

**Issue by patricecolet** [pure-data/deken#282]
```
% developer/deken install freeverb~ 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/patricecolet/.deken/deken.hy", line 207
    (setv repls (dfor #( k v) repls [(re.escape k) v]))
                                    ^
hy.errors.HySyntaxError: parse error for pattern macro 'dfor': got unexpected end of input, expected: some(...)
```

**Comment by zepadovani** [comment]
Hi, I'm having a similar issue trying to install deken through the wget method in Manjaro (5.15.78-1-MANJARO #1 SMP PREEMPT Thu Nov 10 20:50:09 UTC 2022 x86_64 GNU/Linux).

After downloading and adding it to the path, when I run `deken --help`, I get a very similar error:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/padovani/.deken/deken.hy", line 207
    (setv repls (dfor #( k v) repls [(re.escape k) v]))
                                    ^
hy.errors.HySyntaxError: parse error for pattern macro 'dfor': got unexpected end of input, expected: some(...)
`

By now I have succeeded to upload my package by using the docker image, but it seems to be a bug (could it be related to the python version?)

**Comment by umlaeute** [comment]
More likely it's related to set another incompatibility in`hy`

**Comment by umlaeute** [comment]
Could you find out which exact version of `hy` got installed?
Maybe running the `hy` command found in `~/.deken/.../bin` is enough (I'm currently afk and cannot check the exact path)

**Comment by zepadovani** [comment]
`
$ .deken/virtualenv/bin/hy -v                                                                                    
hy 0.25.0
`

(not sure if it is relevant: the one on my /usr/bin is hy 1.0a4)

**Comment by umlaeute** [comment]
Weird. It should be hy-0.24.x (which is newer than 1.0a4, die to $reasons)

I guess the version restriction on requirements.txt is too lax.

Probably time to update the codebase to hy-0.25
