### ISSUE TITLE
install foreign architectures / older versions

### ISSUE THREAD

**Issue by porres** [pure-data/deken#286]
I guess I mentioned this before somewhere and didn't follow through.

Unless something crazy is happening, I believe deken has been quite simlpified to not allow anymore for us to download foreign architectures / older versions.

On a fresh install of Pd 0.53-1 (mojave 10.14.6) I can only find packages for my mac and only the latest version. This usually doesn't bother me, but... 

Maybe there's a way, but anyway, here's a screenshot, what am I missing? 

![Screen Shot 2023-03-10 at 21 33 15](https://user-images.githubusercontent.com/5360142/224453916-3ba138a4-0c2f-4421-adc7-42f5a587e715.png)

**Comment by umlaeute** [comment]
Deken preferences -> untick the "Only show the newest version if a library" item at the bottom.

**Comment by porres** [comment]
I don't see "Deken preferences", where is it?

**Comment by umlaeute** [comment]
in the menu

mfg.gss.owh
IOhannes

**Comment by porres** [comment]
I have to give you some screenshots again... either something funny is happening, or I cannot find it anywhere and you're gonna have to give me detailed baby steps to find this.

![Screen Shot 2023-03-12 at 04 58 21](https://user-images.githubusercontent.com/5360142/224531984-4579fc3f-75da-491c-ba90-601a4a0eec96.png)


![Screen Shot 2023-03-11 at 19 34 33](https://user-images.githubusercontent.com/5360142/224532000-41c2098a-4fdc-420b-8006-7251cef74288.png)


I canot find this entry menu/preferences entry *anywhere* 

![Screen Shot 2023-03-12 at 05 00 51](https://user-images.githubusercontent.com/5360142/224532076-edc135a9-bca5-4aed-af24-41fd7aafe799.png)


macOS 10.14.6, mojave, macbook air 2013...

**Comment by umlaeute** [comment]
Thanks for the screenshots

>I canot find this entry menu/preferences entry *anywhere* 
>

If you open the deken-window, there is a *different* menu, that only contains two top-level entries.

(Your screenshot omits the menu-bar for the case, where the deken-window has focus)

**Comment by porres** [comment]
sorry but at this point I think I need a video or something...

wait wait wait...

and when I was about to ask you again I finally see it, by pure accident, and understand what you mean now by "Your screenshot omits the menu-bar for the case, where the deken-window has focus" :)

I guess we really need to put this in the manual :) or put 'preferences'/'install file' in the main window (but now that I know where this lives I also like that the main window is quite clean).

--------------

Now....... hmmmm.... I tried unchecking 'hide foreign architectures but I can see them. I'm only getting 'macOS' for 'dnd-plugin', but deken site shows me there's more options...

 
![Screen Shot 2023-03-12 at 11 32 05](https://user-images.githubusercontent.com/5360142/224551485-1365e735-d85f-47a7-bcc2-fd4f02484b62.png)

**Comment by porres** [comment]
sorry sorry sorry, I see them now listed below!!!

sorry for so many questions, time to write a deken manual :)
