### ISSUE TITLE
provide object list, and how to add non 'deken generated' object list?

### ISSUE THREAD

**Issue by porres** [pure-data/deken#287]
I'd like to know the details on how deken generates an object list

I'd also like that this list could be downloaded with the package, this could be used by plugins like 'completion' plugin

And I wonder how can we provide this list of objects with their real description instead of getting 'deken generated' as the description info.

**Comment by umlaeute** [comment]
- For the details on the object list format, see the [documentation](https://github.com/pure-data/deken/blob/main/developer/README.md#objectlists).
To include a manually written object list, check the help of the deken cmdline tool
- For details on how the object list is generated, read the source.
- To avoid the"DEKEN GENERATED" stubs, use proper help patches with "meta" information

**Comment by umlaeute** [comment]
> I'd also like that this list could be downloaded with the package, this could be used by plugins like 'completion' plugin

I'd rather have all libraries use an existing quasi-standard (however unknown), than propagate yet another standard (that is likely to not get adapted widely either).

The sole reason why the object list is there, is that we do not have to unzip the package on the server to do the generation there (and there's actually multiple servers involved that do not share the same files, so unzipping would really be a hog)

**Comment by umlaeute** [comment]
> For details on how the object list is generated, read the source.

well, to lift the secret, this is how `deken` (the cmdline tool) generates the object list (if none is provided):
- for each help-patch (`<obj>-help.pd`) an entry is created
- the help-patch is parsed for a `[pd META]` subpatch, and if it finds a comment starting with `DESCRIPTION` this is what gets into the object description
- if there's no `DESCRIPTION` comment, the description is set to "DEKEN GENERATED"

in practice, we do not parse for a `[pd META]` subpatch, but use any comment that starts with `DESCRIPTION` (but this might change any time, so please do use the `[pd META]` subpatch)

**Comment by umlaeute** [comment]
i'm going to close this.
- i think the *question* raised here ("how is the object-list generated") has been answered (parse the DESCRIPTION tag inthe [pd META] subpatch in the help-file) - `done`
- i think the *other question* raised here ("how can i create an object-list manually") has been answered as well (
- it's a text file with each line consisting of an object-name and a description, separated by TAB) - `done`
- i don't think i will implement the suggestion of downloading the object-list for local consumption of other plugins (instead these plugins should parse the [pd META] subpatch in the help-file as well) - `wontfix`
