### ISSUE TITLE
sha256 verification fails on (some) Windows11

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#299]
on some (but not all) Win11 installations of Pd-0.54-1 (which comes with deken-v0.9.14), installing packages fails with a checksum error:

![checksum](https://github.com/pure-data/deken/assets/214034/c797d430-566b-4d34-a986-b60814baf085)

the underlying issue is, that we are using the following command to get the SAH256 fast:
```sh
certUtil -hashfile ${filename} SHA256 | findstr /v "hash"
```

on some versions of Windows, this gives us just the checksum:
```
4ec3d3cd62567f00746d5457dd35ea9f00f57b37b7271ec202cb2dd52854a802
```

but on others we get something like:
```
SHA256 hash of file C:\path\to\iemguts.dek: 4ec3d3cd62567f00746d5457dd35ea9f00f57b37b7271ec202cb2dd52854a802
```
 (that's from the top of my head; in any case, the filename of the checked file is part of the string)

since the output of the command is compared literally to the reference checksum (`4ec3d3cd62567f00746d5457dd35ea9f00f57b37b7271ec202cb2dd52854a802`), the latter obviously fails (due to the leading "garbage").

**Comment by umlaeute** [comment]
maybe one of our windows gurus (@Lucarda, @Spacechild1 ) could shed some light on how to the SHA256 of a file in a stable way across windows versions.

**Comment by umlaeute** [comment]
a quick workaround is to temporarily disable the checksum verification.

0. start Pd
1. open the deken package manager: <kbd>Help</kbd>-><kbd>Find externals</kbd>
2. open the deken preferences window open the **deken preferences** via <kbd>Edit</kbd>-><kbd>Preferences...</kbd>
3. in the "Installation options" section uncheck the checksum verification
    > [ ] Try to verify the libraries' checksum before (re)installing them
4. Click <kbd>OK</kbd> to apply the new settings

this should only be a *temporary* workaround, as it's much better to verify the checksum

**Comment by umlaeute** [comment]
probably the easiest *fix* for the problem is to just check whether the reference hash is *contained* in the calculated checksum

```tcl
if { [string first ${reference} ${hash}] gt 0 } {
```

this makes the verification immune against leading and trailing extra-information, but somewhat weakens the checksum verification.

**Comment by Lucarda** [comment]
Not sure if this helps but using `powershell Get-FileHash` instead of `certUtil` will most likely always? ( i mean in all Windows) output 3 tokens?: 


`powershell Get-FileHash -Algorithm SHA256 "C:\Users\lucarda\Downloads\test.pd" | findstr SHA256`


`SHA256          965232929D33B3C476AA76547CB26BE50F6447EC41E683B003D8DEB2ACEEEBE2       C:\Users\...`

**Comment by umlaeute** [comment]
`Get-FileHash` seems nice, esp when piping to `Format-List`

however, [somewhere](https://wiki.tcl-lang.org/page/Windows+PowerShell) i've read that we cannot use `powershell` from `wish` (as opposed to from `tclsh`).

this seems to be confirmed with something like this:

```tcl
set hashfile [file nativename [file join $::sys_guidir pd_deken.tcl]]
set hash [exec powershell Get-FileHash -Algorithm SHA256 ${hashfile}]
::pdwindow::post "SHA256 ${hash}\n"
```

which just leaves the `$hash` empty (I've deliberately not piped this to `FindStr`, to get the full string)

**Comment by Lucarda** [comment]
Looks like https://github.com/pure-data/deken/issues/299#issuecomment-1820930379 should be done. :)

There's also the option to have some [32bit exe or dll](https://github.com/LekKit/sha256) that could be placed in `pdprototype.tgz` but the above is easier.

**Comment by Lucarda** [comment]
there is also this hack (not nice i think):

`c:/tmp/hash.bat`
```
@echo off
powershell -Command " & {Get-FileHash -Algorithm SHA256 %1  | Select-Object -ExpandProperty Hash} > %temp%\hash.txt
type %temp%\hash.txt
```


```
set hash [exec c:/tmp/hash.bat ${hashfile}]

```

**Comment by umlaeute** [comment]
this *almost* works (once you add additional quotes around `%1`), but only as long as the filename does not contain square brackets (e.g. `hash.bat zexy[2.4.2].dek` returns an empty string, presumably because the brackets are interpreted as some array dereference or whatever).
any ideas? (short of renaming all the files?)

**Comment by umlaeute** [comment]
deken v0.9.16 fixes the issue.
to manually install it on Windows do this:

1. manually download deken v0.9.16
   1. **EITHER** do this via Pd
       1. start Pd, open <kbd>Find externals...</kbd>
       3. search for `deken-plugin`
       4. expand the search results to see the list of all results
       5. <kbd>right-click</kbd> the latest and greatest release and click on <kbd>Copy package URL</kbd>
       6. Open your favourite browser and paste the copied URL
       7. download the file
   3. **OR** just download it from [here](http://puredata.info/Members/zmoelnigbot/software/deken-plugin/0.9.16/deken-plugin%5Bv0.9.16%5D.dek)
2. start Pd, open <kbd>Find externals...</kbd>
3. in the deken-window, open the <kbd>File</kbd> menu and select <kbd>Install DEK file...</kbd>
4. select the downloaded file `deken-plugin[v0.9.16].dek`
5. install the package

You should now have a fixed version of deken.
After a restart of Pd, you should now be able to normally install packages *with* SHA256 verification.

**Comment by Lucarda** [comment]
thanks. i tried it and is working fine for me.

i could not download the file via:

>ii. OR just download it from here

i got the file from the deken `Copy package URL` and then installed the `.dek` file.

**Comment by umlaeute** [comment]
> i could not download the file via:

ah, that's because i posted n `http` link and modern browsers don't allow downloading via `http` from `https`. (at least in firefox you have to manually whitelist each file downloaded via `http`).
Anyhow, i've now updated the link to use `https`, which should work...

**Comment by musger** [comment]
I can just add that a colleague was trying to install 'hidio' from Deken on his Windows
machine yesterday. He gets a checksum error (german "Fehler") reported as

Checksummen-Fehler für 'hidio[v0.20200224](Windows-amd64-32)(Sources).dek'

and installation fails. He will try the manual fix proposed.

**Comment by musger** [comment]
* Peter P. ***@***.***> [2024-03-07 15:50]:
[...]
> > Having said that, the *Sources* package they were downloading, were probably off little use anyhow...
> Ah darn, just what I suspected. Another source of confusion for
> beginners maybe? Can downloading of sources instead of binaries be
> disabled (as in eg. apt's sources list) for Deken as a (default) option already?
Or could it be made more clear the package is sources only instead of
hiding this info in the version string somewhere?
b,P

**Comment by umlaeute** [comment]
well, if there's a source-only package, it will not be displayed by default.
if the user deliberately unticks the `Hide foreign architectures` checkbox in the deken-preferences, it will be shown but with a light-grey color, indicating that this is not the preferred choice.

so i think we are already doing enough to keep users from confusion.

now, having said that i have now checked which `hidio` packages are *actually* available: http://deken.puredata.info/library/hidio
it turns out, that the *only* available package is a `Windows-amd64-32`/`Sources` packages, so it does contain Win64 binaries (and doesn't shouldn't require re-compilation).

I now see, that the `Windows-amd64-32` portion of the architecture was just swallowed by github's markdown renderer (and i didn't check the raw text you posted). i've updated your post accordingly.
sorry for the noise.

**Comment by musger** [comment]
Thanks,
understood. I was just puzzled that the Win binary package has "Sources"
in its name, which I think should be avoided (but I guess I'd have to
tell this to the package maintainer her/himself). Unless there are
standardized naming schemes for packages unknown to me.

much appreciated,
P

* umläute ***@***.***> [2024-03-08 08:14]:

**Comment by umlaeute** [comment]
Why should it avoid "Sources"?

The part in parens is the "architecture", and a special architecture is the "sources" arch, which means: this package contains the source code (just like "Windows-pdp11-32" means: this package contains binaries for windows running on a pdp11, using single precision).

So: If the package does contain the sources, it should also contain the "Sources" specifier on the arch string.

**Comment by Lucarda** [comment]
@musger thers is nothing bad or wrong in including sources in a deken package.

iirc this particular package is the *only* hidio version that works for Windows. Martin Peach did it in the pandemic just before he passed away. the deken pkg is the only source for its source.
