### ISSUE TITLE
Install from DEK Not working on macOS 

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#300]
It seems that on macOS the "install from DEK file" via the <kbd>File</kbd> menu (for the deken window) does not work at all: no file selector is opened.

Afaict the problem is, that the file selector crashes if there's an extension with two dots, like `.tar.gz`.

Can some macOS person confirm this? (ping @porres)

**Comment by porres** [comment]
Install from DEK did give me an "openpanel", macos mojave

![Screen Shot 2023-12-23 at 21 30 47](https://github.com/pure-data/deken/assets/5360142/d88cb058-809a-4534-8f48-3dca0ed77a44)

**Comment by 60-hz** [comment]
Confirm a crash under MacOS Sonoma 14.0
