### ISSUE TITLE
deken not showing foreign architectures

### ISSUE THREAD

**Issue by porres** [pure-data/deken#304]
hi, on an arm mac and pd 0.55-2 I can't see libraries that are not for my architecture even if in the preferences I don't have 'hide foreign architectures' checked.

I just get, for instance:

Searching for "creb"...
Searching on http://deken.puredata.info/search...
Searching on http://deken.puredata.info/search returned 8 results
"creb": Found 0 usable packages (of 7 packages in total).
It appears that there are no matching packages for your architecture.

**Comment by porres** [comment]
actually, the problem is that it goes to the 'log' tab when it doesn't find anything, and it can confuse us... I guess this is intentional though, huh?

**Comment by umlaeute** [comment]
yes this is intentional
