### ISSUE TITLE
show download link before starting the download

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#33]
it would be nice to see the actual download link before clicking on it.
e.g. in a statusbar or via a balloon text.

**Comment by umlaeute** [comment]
that's for two reasons:
- be able to distinguish between multiple uploads by the same person
- if we ever support more than one package source (aka "repository" in Debian speek), a description "foo-1.2.3; uploaded by bar in 1984" becomes less unique than it is now (btw, we should indicate the repository as well)
- currently, the "title" of the downloadable file on puredata.info may differ from the actual filename.
esp. in the "downloads" section titles like"universal builds" are encouraged, as the library/version are clear by the context.

**Comment by danomatika** [comment]
I agree on the status bar, like in web browsers.

**Comment by umlaeute** [comment]
and while thinking web-browsers, wouldn't it be nice to also be able to just copy the URL to the clipboard via right-click?

**Comment by chr15m** [comment]
:+1:
