### ISSUE TITLE
Pd hangs when destination folder already exists

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#46]
When I download a package that wants to extract to a folder that already
exists, the plugin hangs and with it whole Pd.

Scenario to trigger this situation:
* Menu > Help > Find externals
* search zexy
* pick wrong architecture
* restart Pd (zexy won't load)
* open 'find externals' again, search for zexy
* pick correct architecture
 
Pd hangs now.

**Comment by chr15m** [comment]
dup of #44 - fixed.

**Comment by chr15m** [comment]
dup of #44 - fixed.
