### ISSUE TITLE
The search results order should put "matched" externals first.

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#5]

**Comment by umlaeute** [comment]
assuming that "matched" means "externals including binaries for the *local* OS and architecture": :+1: 

the user really should be able to distinguish between compatible and incompatible versions (with resp. to their host system) of the external.

**Comment by chr15m** [comment]
Yep, that's what this feature is aiming for.

**Comment by chr15m** [comment]
Instead of filtering out non-matching OS entirely we should keep all of the non-matching-architecture results in the list and clicking should be a download link to the zip/tgz file so the user could obtain externals for a different platform than the one they are on, if they need to.

**Comment by danomatika** [comment]
You could also grey out non-matching architectures and darken the text on mouse over as visual feedback. Or am I thinking to web design now? :)

**Comment by chr15m** [comment]
The plugin already does that. :)
