### ISSUE TITLE
windows plugin install folder

### ISSUE THREAD

**Issue by jmmmp** [pure-data/deken#53]
I'm not sure if %AppData%\Pd works, as the Pd folder isn't in the pd path. %AppData%/Pd/extra works for sure.
Also, windows paths have /, not \.

**Comment by umlaeute** [comment]
no, `%AppData%/Pd/extra` certainly will **not** work unless you have:
- added it manually to your search-paths *OR*
- installed Pd into `%AppData%` (which is not the recommended thing to do, butnobody can keep you from doing it).

in any case, deken get's the list of search folders directly from Pd and uses that (though there was #49 that prevented this to work in a foolproof; it's currently awaiting @chr15m review - hint, hint)
