### ISSUE TITLE
Sort discovered externals by version first and then date.

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#62]

**Comment by umlaeute** [comment]
sort-by-version has been implemented in [3589890cbbf9fc3418dc949c4418b7e610a0441c].

actually it sorts sorts by filename, but since filename have the pattern `<pkgname>-<version>-...` it sorts by version but groups by pkgname (which makes sense).

**Comment by chr15m** [comment]
Ah ok, I missed that. Good. Will that work for a version like: 9.1.1 versus 10.1.1?

**Comment by umlaeute** [comment]
try it out :-)

but, yes it should work. the magic option is `-dictionary`

**Comment by chr15m** [comment]
ah cool.
