### ISSUE TITLE
refactor gpg-signing: move into "package"

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#65]
currently the gpg signing is done in the `upload` subcommand, but i really think that it should go into the `package` subcommand (where the zipping is done).

- `package`: prepare (all) files for uploading
- `upload`: send (all) files to remote

as a side-effect, this might make it easier to batch-sign a number of packages, using `gpg-agent` or whatever, before actually doing the `upload`.

if `upload` detects missing `md5` and `asc` files, it could attempt to create them (but that would be out of the ordinary workflow)

**Comment by chr15m** [comment]
:+1:

**Comment by chr15m** [comment]
```
use_agent (defaults to False)
    If specified as True, the --use-agent parameter is passed to GPG, asking it to use any in-memory GPG agent (which remembers your credentials).
```
