### ISSUE TITLE
UNHANDLED ERROR Darwin-x86_64-32bit

### ISSUE THREAD

**Issue by megrimm** [pure-data/deken#68]
hey just tried this out again and getting:

deken-plugin.tcl (Pd externals search) in /Users/megrimm/Library/Pd loaded.
Platform detected: Darwin-x86_64-32bit
-----------
UNHANDLED ERROR: wrong # args: should be "catch command ?varName?"
    while compiling
"catch { exec lsb_release -si } ::deken::apt::distribution options "
    invoked from within
"if { [ catch { exec lsb_release -si } ::deken::apt::distribution options ] } { unset ::deken::apt::distribution }"
    ("uplevel" body line 465)
    invoked from within
"uplevel #0 $tclcode"
FAILED TO LOAD /Users/megrimm/Library/Pd/deken-plugin.tcl
-----------

I tried a couple weeks ago and that one worked without error.

**Comment by umlaeute** [comment]
deken is moving fast, so "a couple of weeks ago" the code-base was quite different.

I'll try to fix that OSX-specific error, but won't have time until monday...

**Comment by megrimm** [comment]
yes! ...and its really great work your doing! no rush just wanted to point awareness to it....
