### ISSUE TITLE
Debian package "deken"

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#70]
just to open a ticket about the debian packaging of deken. ([ITP: #788075](https://bugs.debian.org/#788075))

**Comment by umlaeute** [comment]
Here's a TODO list:

- [x] packaging dependencies
 - hy==0.11.0
 - sh==1.11
 - [x] easywebdav==1.2.0
 - [x] pyelftools==0.23
 - [x] macholib==1.7
   - [x] altgraph
 - python-gnupg==0.3.7
 - keyring==4.0

- [ ] tagged release of deken
 - Debian really likes it to be able to refer to a specific *release*

**Comment by umlaeute** [comment]
the package will feature two binary (== installable) packages:

- `pd-deken` the GUI-plugin
- `deken` the cmdline tool
 - stripped off functionality: `install`, `upgrade` (both are handled via `apt`)

**Comment by umlaeute** [comment]
today - after taking the liberty of tagging `v0.1` - I uploaded [deken_0.1-1](https://ftp-master.debian.org/new/deken_0.1-1.html) to Debian.

(I'll close this ticket once the package has been *accepted* into Debian)

**Comment by danomatika** [comment]
:D

**Comment by chr15m** [comment]
Excellent! This is the first software I've made a significant contribution to in Debian. Thanks IOhannes!

**Comment by umlaeute** [comment]
`deken` was accepted into Debian today.

**Comment by umlaeute** [comment]
so `deken` is now available in both [Debian](https://packages.debian.org/source/sid/deken) and [Ubuntu (wily werewolf)](http://packages.ubuntu.com/source/wily/deken)!

**Comment by chr15m** [comment]
Excellent!
