### ISSUE TITLE
~/bin/deken does not find python on debian

### ISSUE THREAD

**Issue by ritsch** [pure-data/deken#81]
After 
> curl https://raw.githubusercontent.com/pure-data/deken/master/deken > ~/bin/deken
> chmod 755 ~/bin/deken
> ~/bin/deken
Oops, no Python found! You need Python to run Deken.
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues

Analysis:

on line 76:
   which python >/dev/null && error ...
after python is found the error is executed, so it should be 
   which python >/dev/null || error ...
if you use this kind of python detection

**Comment by umlaeute** [comment]
Btw, a proper "deken" Debian package is in the make...
