### ISSUE TITLE
what's the canonical name for the OSX/PowerPC platform?

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#83]
i just noticed that when i create a deken-package from OSX fat binaries (i386/amd64/ppc) on my Debian box, the architecture string is:

     (Darwin-i386-32)(Darwin-PowerPC-32)(Darwin-x86_64-32)

but when i search for e.g. *cyclone* i get a result from Fred Jan that uses 

     (Darwin-ppc-32)(Darwin-i386-32)(Darwin-x86_64-64)

so apart from the different bittiness on *x86_64*, we have two different arch-strings for ppc: `PowerPC` vs `ppc`.

Which one is the right one?

Should we add a  value to `::deken::architecture_substitutes`?

**Comment by danomatika** [comment]
$0.02

Maybe the better question is why compile for ppc? :D

It will be dependent upon having OS X 10.6 around  ... and 90+% of people who might help in packaging externals in the future will not be using 10.6. I understand the "but people still have the old hardware around point", but it's really not that many to add more hurdles to building/distribution.

**Comment by umlaeute** [comment]
it's all optional. the system already does support many architectures.
if you only build for `linux/arm5hf` then this is fine for deken.

if you do want to build for OSX-10.4/PowerPC, then this is fine for deken as well, and should work.

**Comment by chr15m** [comment]
Hm, that's a weird bug! Will check.

**Comment by chr15m** [comment]
Actually I have a feeling @electrickery might have hand-crafted the filename instead of using Deken. Can you let us know Fred Jan?

Yep, I think we should have an entry in `architecture_substitutes` for whichever one TCL doesn't use.

**Comment by electrickery** [comment]
Hi All,

> Actually I have a feeling @electrickery
> <https://github.com/electrickery> might have hand-crafted the filename
> instead of using Deken. Can you let us know Fred Jan?

Indeed the filenames are hand-crafted. The MacOSX 10.5 has issues with
keys, so deken would not properly install. So I zip the result by hand
and use deken on Linux to upload the result.

If "(Darwin-i386-32)(Darwin-PowerPC-32)(Darwin-x86_64-32)" are the
proper architecture names, I have no problem changing it with the next
update. But is "Darwin-x86_64-32" 32 or 64 bit?
> 
> Yep, I think we should have an entry in |architecture_substitutes| for
> whichever one TCL doesn't use.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pure-data/deken/issues/83#issuecomment-126554957>.
> 

Greetings,

Fred Jan

**Comment by chr15m** [comment]
Ok, thanks. If you run `deken package` against an OSX directory of externals on Linux it will detect and tag the OSX binaries correctly.

I am not sure about the 32/64 bit issue. I think the mach-O library is telling us it was compiled on x86_64 but it has internal 32 bit architecture.

**Comment by umlaeute** [comment]
what do you mean by "*has internal 32bit architecture*"?

i just checked `libGL.dylib` from the *MacOSX10.6.sdk*, and it reports as `(Darwin-i386-32)(Darwin-PowerPC-32)(Darwin-x86_64-32)` as well.

**Comment by chr15m** [comment]
I am not sure what I mean by that. I guess that the binary would only use 32-bit address lookups and assume 32-bit CPU registers?

I don't know what I am talking about.

**Comment by umlaeute** [comment]
hopefully not
