### ISSUE TITLE
Remove OSX rtcmix~ from the repository as it does not work.

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#86]
http://lists.puredata.info/pipermail/pd-list/2015-10/111750.html

**Comment by umlaeute** [comment]
hmm.
i don't think we can (nor should) track any faulty deken libraries out there.

if we are going decentral (and this is one of the big promises of deken), we simply cannot ensure that people won't share garbage.

if somebody uploads a broken package, *they* are responsible for it (even if it was installed via deken).


i suggest to therefore close this ticket.

**Comment by chr15m** [comment]
I 100% agree.

In this case I was the one who uploaded the broken package so felt I should be responsible for it. :)

**Comment by umlaeute** [comment]
any news for this?

**Comment by chr15m** [comment]
The only `rtcmix~` packages I can find on pure-data.info now are owned by jwmatthys:

http://puredata.info/search?SearchableText=rtcmix%7E

I don't know if those work but I no longer feel responsible for them as I did not upload them. Happy to close this.

**Comment by umlaeute** [comment]
i only tested via remote access to an OSX machine, and it crashes as soon as dsp is turned on.
however, since this is out of our hands, i hereby close this.
