### ISSUE TITLE
batch download

### ISSUE THREAD

**Issue by pob31** [pure-data/deken#92]
Take for example if I want to download the whole set of Pd-extended extras, then I have to search for "extended" after each download. It's a bit tedious and it's easy to lose track of what has been downloaded already and what is still to be downloaded.

Would it be possible to either:
- have a separate window to show the download progress and keep the search results at hand. It's easier to keep track of what has been downloaded.
- have sets that make it possible to download all the corresponding archive at once. the user would then have to sort them out on their hard-drive. For example this could be "extended", "linux", "mac osx", "windows", "iem", "pix_" etc...

**Comment by umlaeute** [comment]
i think this is basically resolved: you can now select multiple packages to download in a single run.

we still do not have any way to specify (and search for) "meta-packages", but at least, you do not have to search and re-search.
