### ISSUE TITLE
select multiple packages to download

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#94]
sometimes it would be nice to be able to select multiple packages at once.

e.g. if I search for empty string (ALL packages), then i might want to have an option to install `zexy`, `iemguts` and ... (what else would anybody need? ah yes `Gem`).

probably a table like interface with checkboxes.

**Comment by umlaeute** [comment]
this complements #93

**Comment by umlaeute** [comment]
related to #92

**Comment by chr15m** [comment]
:+1:

**Comment by jreso** [comment]
I have the same issue. If I want to share a "big" project with 10-20 libraries, I would like to make it easier to download all one time. It could be a dependencies file or simplier now, just download for your platform a list of externals with coma : "zexy, Gem, cyclone, mapping, iemguts". Do you think it is possible ?

**Comment by chr15m** [comment]
@jreso I wrote a haiku:

> vapourware, no code.
> feature requests ebb and flow,
> like mist in the wind.

Maybe when #142 gets implemented you could show some info about packages required but I also don't know when that will happen. :man_shrugging:
