### ISSUE TITLE
find a way to integrate development regarding the pd-included deken

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#95]
thanks to @millerpuckette, "deken" (the plugin) is included into pd-vanilla since b55459c38d7392636e880a7bdd1e283ee5eb0351.

i wonder how we should proceed development of the plugin.

**Comment by danomatika** [comment]
Eek. Submodule?

**Comment by millerpuckette** [comment]
Yep, I should have put this out as a question first... but amyway, it would
work fine for me to informally track developments in the deken github
site.

I'm not sure what deken developers would think of the changes I made to the
plug-in (mostly about path selection but I also suppressed the startup
messages which I think would be appropriate in a plug-in but not as a standard
component of Pd).  I can submit a patch if there's interest in having them
upstream.

cheers
Miller

**Comment by chr15m** [comment]
I've posted to pd-list with the pull-request that will enable us to adopt either strategy. It will let @millerpuckette cleanly pull deken commits from here into `pure-data/master` or the other way around.

I am personally happy to work from `tcl/pd_deken.tcl` directly and issue pull requests against `pure-data/master`.

**Comment by umlaeute** [comment]
i guess the *pull request* here means: ordinary patches submitted via the sourceforge patch tracker?

**Comment by umlaeute** [comment]
so it seems that in practice the way it happens is:
- every now and then, @millerpuckette  copies "deken-plugin.tcl`  from `deken:master` to `tcl/pd_deken.tcl` in `pure-data:master`.

this works ok, as long as
- `deken:master` is (always) in a releasable state
- `deken:master` is *never* behind `pure-data:master`

**Comment by umlaeute** [comment]
to allow the development version (`deken:master`) to override the Pd-bundled version, there now is a simplistic version scheme built into the plugin: `::deken::versioncheck` compares the version of the plugin-being-loaded with the version of any plugin-already-loaded and will refuse to load if the plugin-being-loaded is not newer.

this means, that the line

    if { [::deken::versioncheck 0.2] } {

should get the version incremented whenever the first new feature/bugfix is done after an import into `pure-data`.
