### ISSUE TITLE
how to delete wrong password?

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#97]
It seems deken stores the password in a keyring when uploading packages. However, there seems to be no check wether the password is valid. Once it is set, it won't ask for the password any more and will continue to use the wrong password.

Also, it's not clear where those passwords are stored.

**Comment by danomatika** [comment]
See https://github.com/pure-data/deken/issues/96

**Comment by umlaeute** [comment]
yep. the idea is that you tell deken to ask for the password (`--ask-password`); it will then update the keyring with the new password.

**Comment by reduzent** [comment]
Thanks, and sorry for the noise.
